// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/pb/auth_subscription.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthSubscriptionService_FetchUserMetaData_FullMethodName   = "/auth_subscription.AuthSubscriptionService/FetchUserMetaData"
	AuthSubscriptionService_CheckUserListExists_FullMethodName = "/auth_subscription.AuthSubscriptionService/CheckUserListExists"
)

// AuthSubscriptionServiceClient is the client API for AuthSubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthSubscriptionServiceClient interface {
	// rpc CheckUserExists(CheckUserExistsRequest) returns (CheckUserExistsResponse);
	FetchUserMetaData(ctx context.Context, in *UserDataReq, opts ...grpc.CallOption) (*BatchUserMetadataResponse, error)
	CheckUserListExists(ctx context.Context, in *UserDataReq, opts ...grpc.CallOption) (*BatchUserExistResponse, error)
}

type authSubscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthSubscriptionServiceClient(cc grpc.ClientConnInterface) AuthSubscriptionServiceClient {
	return &authSubscriptionServiceClient{cc}
}

func (c *authSubscriptionServiceClient) FetchUserMetaData(ctx context.Context, in *UserDataReq, opts ...grpc.CallOption) (*BatchUserMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUserMetadataResponse)
	err := c.cc.Invoke(ctx, AuthSubscriptionService_FetchUserMetaData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSubscriptionServiceClient) CheckUserListExists(ctx context.Context, in *UserDataReq, opts ...grpc.CallOption) (*BatchUserExistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUserExistResponse)
	err := c.cc.Invoke(ctx, AuthSubscriptionService_CheckUserListExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSubscriptionServiceServer is the server API for AuthSubscriptionService service.
// All implementations must embed UnimplementedAuthSubscriptionServiceServer
// for forward compatibility.
type AuthSubscriptionServiceServer interface {
	// rpc CheckUserExists(CheckUserExistsRequest) returns (CheckUserExistsResponse);
	FetchUserMetaData(context.Context, *UserDataReq) (*BatchUserMetadataResponse, error)
	CheckUserListExists(context.Context, *UserDataReq) (*BatchUserExistResponse, error)
	mustEmbedUnimplementedAuthSubscriptionServiceServer()
}

// UnimplementedAuthSubscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthSubscriptionServiceServer struct{}

func (UnimplementedAuthSubscriptionServiceServer) FetchUserMetaData(context.Context, *UserDataReq) (*BatchUserMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchUserMetaData not implemented")
}
func (UnimplementedAuthSubscriptionServiceServer) CheckUserListExists(context.Context, *UserDataReq) (*BatchUserExistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserListExists not implemented")
}
func (UnimplementedAuthSubscriptionServiceServer) mustEmbedUnimplementedAuthSubscriptionServiceServer() {
}
func (UnimplementedAuthSubscriptionServiceServer) testEmbeddedByValue() {}

// UnsafeAuthSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthSubscriptionServiceServer will
// result in compilation errors.
type UnsafeAuthSubscriptionServiceServer interface {
	mustEmbedUnimplementedAuthSubscriptionServiceServer()
}

func RegisterAuthSubscriptionServiceServer(s grpc.ServiceRegistrar, srv AuthSubscriptionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthSubscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthSubscriptionService_ServiceDesc, srv)
}

func _AuthSubscriptionService_FetchUserMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSubscriptionServiceServer).FetchUserMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSubscriptionService_FetchUserMetaData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSubscriptionServiceServer).FetchUserMetaData(ctx, req.(*UserDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSubscriptionService_CheckUserListExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSubscriptionServiceServer).CheckUserListExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSubscriptionService_CheckUserListExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSubscriptionServiceServer).CheckUserListExists(ctx, req.(*UserDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthSubscriptionService_ServiceDesc is the grpc.ServiceDesc for AuthSubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthSubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_subscription.AuthSubscriptionService",
	HandlerType: (*AuthSubscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchUserMetaData",
			Handler:    _AuthSubscriptionService_FetchUserMetaData_Handler,
		},
		{
			MethodName: "CheckUserListExists",
			Handler:    _AuthSubscriptionService_CheckUserListExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/auth_subscription.proto",
}
