// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/pb/auth_subscription.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoesUserExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoesUserExistsRequest) Reset() {
	*x = DoesUserExistsRequest{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoesUserExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoesUserExistsRequest) ProtoMessage() {}

func (x *DoesUserExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoesUserExistsRequest.ProtoReflect.Descriptor instead.
func (*DoesUserExistsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *DoesUserExistsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DoesUserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=Exists,proto3" json:"Exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoesUserExistsResponse) Reset() {
	*x = DoesUserExistsResponse{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoesUserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoesUserExistsResponse) ProtoMessage() {}

func (x *DoesUserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoesUserExistsResponse.ProtoReflect.Descriptor instead.
func (*DoesUserExistsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *DoesUserExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UserDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []uint64               `protobuf:"varint,1,rep,packed,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataReq) Reset() {
	*x = UserDataReq{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataReq) ProtoMessage() {}

func (x *UserDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataReq.ProtoReflect.Descriptor instead.
func (*UserDataReq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *UserDataReq) GetUserId() []uint64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

type BatchUserExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []uint64               `protobuf:"varint,1,rep,packed,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUserExistResponse) Reset() {
	*x = BatchUserExistResponse{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUserExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUserExistResponse) ProtoMessage() {}

func (x *BatchUserExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUserExistResponse.ProtoReflect.Descriptor instead.
func (*BatchUserExistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *BatchUserExistResponse) GetUserId() []uint64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

type BatchUserMetadataResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Users         map[uint64]*UserMetadata `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUserMetadataResponse) Reset() {
	*x = BatchUserMetadataResponse{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUserMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUserMetadataResponse) ProtoMessage() {}

func (x *BatchUserMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUserMetadataResponse.ProtoReflect.Descriptor instead.
func (*BatchUserMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *BatchUserMetadataResponse) GetUsers() map[uint64]*UserMetadata {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ProfileImgUrl string                 `protobuf:"bytes,4,opt,name=ProfileImgUrl,proto3" json:"ProfileImgUrl,omitempty"`
	BlueTick      bool                   `protobuf:"varint,5,opt,name=BlueTick,proto3" json:"BlueTick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMetadata) Reset() {
	*x = UserMetadata{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMetadata) ProtoMessage() {}

func (x *UserMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMetadata.ProtoReflect.Descriptor instead.
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *UserMetadata) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserMetadata) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMetadata) GetProfileImgUrl() string {
	if x != nil {
		return x.ProfileImgUrl
	}
	return ""
}

func (x *UserMetadata) GetBlueTick() bool {
	if x != nil {
		return x.BlueTick
	}
	return false
}

var File_pkg_pb_auth_subscription_proto protoreflect.FileDescriptor

const file_pkg_pb_auth_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/pb/auth_subscription.proto\x12\x11auth_subscription\"/\n" +
	"\x15DoesUserExistsRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"0\n" +
	"\x16DoesUserExistsResponse\x12\x16\n" +
	"\x06Exists\x18\x01 \x01(\bR\x06Exists\"%\n" +
	"\vUserDataReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x03(\x04R\x06UserId\"0\n" +
	"\x16BatchUserExistResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x03(\x04R\x06UserId\"\xc5\x01\n" +
	"\x19BatchUserMetadataResponse\x12M\n" +
	"\x05users\x18\x01 \x03(\v27.auth_subscription.BatchUserMetadataResponse.UsersEntryR\x05users\x1aY\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.auth_subscription.UserMetadataR\x05value:\x028\x01\"\x98\x01\n" +
	"\fUserMetadata\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12$\n" +
	"\rProfileImgUrl\x18\x04 \x01(\tR\rProfileImgUrl\x12\x1a\n" +
	"\bBlueTick\x18\x05 \x01(\bR\bBlueTick2\xc5\x02\n" +
	"\x17AuthSubscriptionService\x12a\n" +
	"\x11FetchUserMetaData\x12\x1e.auth_subscription.UserDataReq\x1a,.auth_subscription.BatchUserMetadataResponse\x12`\n" +
	"\x13CheckUserListExists\x12\x1e.auth_subscription.UserDataReq\x1a).auth_subscription.BatchUserExistResponse\x12e\n" +
	"\x0eDoesUserExists\x12(.auth_subscription.DoesUserExistsRequest\x1a).auth_subscription.DoesUserExistsResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_auth_subscription_proto_rawDescOnce sync.Once
	file_pkg_pb_auth_subscription_proto_rawDescData []byte
)

func file_pkg_pb_auth_subscription_proto_rawDescGZIP() []byte {
	file_pkg_pb_auth_subscription_proto_rawDescOnce.Do(func() {
		file_pkg_pb_auth_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_auth_subscription_proto_rawDesc), len(file_pkg_pb_auth_subscription_proto_rawDesc)))
	})
	return file_pkg_pb_auth_subscription_proto_rawDescData
}

var file_pkg_pb_auth_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_pb_auth_subscription_proto_goTypes = []any{
	(*DoesUserExistsRequest)(nil),     // 0: auth_subscription.DoesUserExistsRequest
	(*DoesUserExistsResponse)(nil),    // 1: auth_subscription.DoesUserExistsResponse
	(*UserDataReq)(nil),               // 2: auth_subscription.UserDataReq
	(*BatchUserExistResponse)(nil),    // 3: auth_subscription.BatchUserExistResponse
	(*BatchUserMetadataResponse)(nil), // 4: auth_subscription.BatchUserMetadataResponse
	(*UserMetadata)(nil),              // 5: auth_subscription.UserMetadata
	nil,                               // 6: auth_subscription.BatchUserMetadataResponse.UsersEntry
}
var file_pkg_pb_auth_subscription_proto_depIdxs = []int32{
	6, // 0: auth_subscription.BatchUserMetadataResponse.users:type_name -> auth_subscription.BatchUserMetadataResponse.UsersEntry
	5, // 1: auth_subscription.BatchUserMetadataResponse.UsersEntry.value:type_name -> auth_subscription.UserMetadata
	2, // 2: auth_subscription.AuthSubscriptionService.FetchUserMetaData:input_type -> auth_subscription.UserDataReq
	2, // 3: auth_subscription.AuthSubscriptionService.CheckUserListExists:input_type -> auth_subscription.UserDataReq
	0, // 4: auth_subscription.AuthSubscriptionService.DoesUserExists:input_type -> auth_subscription.DoesUserExistsRequest
	4, // 5: auth_subscription.AuthSubscriptionService.FetchUserMetaData:output_type -> auth_subscription.BatchUserMetadataResponse
	3, // 6: auth_subscription.AuthSubscriptionService.CheckUserListExists:output_type -> auth_subscription.BatchUserExistResponse
	1, // 7: auth_subscription.AuthSubscriptionService.DoesUserExists:output_type -> auth_subscription.DoesUserExistsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_auth_subscription_proto_init() }
func file_pkg_pb_auth_subscription_proto_init() {
	if File_pkg_pb_auth_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_auth_subscription_proto_rawDesc), len(file_pkg_pb_auth_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_auth_subscription_proto_goTypes,
		DependencyIndexes: file_pkg_pb_auth_subscription_proto_depIdxs,
		MessageInfos:      file_pkg_pb_auth_subscription_proto_msgTypes,
	}.Build()
	File_pkg_pb_auth_subscription_proto = out.File
	file_pkg_pb_auth_subscription_proto_goTypes = nil
	file_pkg_pb_auth_subscription_proto_depIdxs = nil
}
