apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
type: Opaque
stringData:
  # Security Keys
  USER_SECURITY_KEY: ""
  ADMIN_SECURITY_KEY: ""
  OTPVERIFICATION_SECURITY_KEY: ""
  RESET_PASSWORD_SECURITY_KEY: ""
  ADMIN_REFRESH_KEY: ""
  USER_REFRESH_KEY: ""
  # External Integrations
  REDIS_ADDRESS: "" # Typical Bitnami Redis service name
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
  RAZORPAY_WEBHOOK_SECRET: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
---