apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  # Using stringData so you can enter plain text; K8s will base64 it for you.
  DB_PASSWORD: ""
  KAFKA_CA_CERT: 
  KAFKA_ACCESS_CERT: 
  KAFKA_ACCESS_KEY: 
---