apiVersion: v1
kind: Secret
metadata:
  name: post-relation-secret
type: Opaque
stringData: # stringData allows plain text; K8s encodes it to base64 automatically
  DB_PASSWORD: ""
  REDIS_ADDRESS: "" # Typical Bitnami Redis service name
  KAFKA_CA_CERT: 
  KAFKA_ACCESS_CERT: 
  KAFKA_ACCESS_KEY: 
---