// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/pb/auth_subscription.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckUserExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistsRequest) Reset() {
	*x = CheckUserExistsRequest{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistsRequest) ProtoMessage() {}

func (x *CheckUserExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckUserExistsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUserExistsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckUserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistsResponse) Reset() {
	*x = CheckUserExistsResponse{}
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistsResponse) ProtoMessage() {}

func (x *CheckUserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckUserExistsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUserExistsResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_pkg_pb_auth_subscription_proto protoreflect.FileDescriptor

const file_pkg_pb_auth_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/pb/auth_subscription.proto\x12\x11auth_subscription\"0\n" +
	"\x16CheckUserExistsRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"1\n" +
	"\x17CheckUserExistsResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId2\x83\x01\n" +
	"\x17AuthSubscriptionService\x12h\n" +
	"\x0fCheckUserExists\x12).auth_subscription.CheckUserExistsRequest\x1a*.auth_subscription.CheckUserExistsResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_auth_subscription_proto_rawDescOnce sync.Once
	file_pkg_pb_auth_subscription_proto_rawDescData []byte
)

func file_pkg_pb_auth_subscription_proto_rawDescGZIP() []byte {
	file_pkg_pb_auth_subscription_proto_rawDescOnce.Do(func() {
		file_pkg_pb_auth_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_auth_subscription_proto_rawDesc), len(file_pkg_pb_auth_subscription_proto_rawDesc)))
	})
	return file_pkg_pb_auth_subscription_proto_rawDescData
}

var file_pkg_pb_auth_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_auth_subscription_proto_goTypes = []any{
	(*CheckUserExistsRequest)(nil),  // 0: auth_subscription.CheckUserExistsRequest
	(*CheckUserExistsResponse)(nil), // 1: auth_subscription.CheckUserExistsResponse
}
var file_pkg_pb_auth_subscription_proto_depIdxs = []int32{
	0, // 0: auth_subscription.AuthSubscriptionService.CheckUserExists:input_type -> auth_subscription.CheckUserExistsRequest
	1, // 1: auth_subscription.AuthSubscriptionService.CheckUserExists:output_type -> auth_subscription.CheckUserExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_auth_subscription_proto_init() }
func file_pkg_pb_auth_subscription_proto_init() {
	if File_pkg_pb_auth_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_auth_subscription_proto_rawDesc), len(file_pkg_pb_auth_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_auth_subscription_proto_goTypes,
		DependencyIndexes: file_pkg_pb_auth_subscription_proto_depIdxs,
		MessageInfos:      file_pkg_pb_auth_subscription_proto_msgTypes,
	}.Build()
	File_pkg_pb_auth_subscription_proto = out.File
	file_pkg_pb_auth_subscription_proto_goTypes = nil
	file_pkg_pb_auth_subscription_proto_depIdxs = nil
}
