// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/pb/post_relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostFollowCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostFollowCountRequest) Reset() {
	*x = PostFollowCountRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFollowCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFollowCountRequest) ProtoMessage() {}

func (x *PostFollowCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFollowCountRequest.ProtoReflect.Descriptor instead.
func (*PostFollowCountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{0}
}

func (x *PostFollowCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PostFollowCountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PostCount      uint64                 `protobuf:"varint,1,opt,name=PostCount,proto3" json:"PostCount,omitempty"`
	FollowerCount  uint64                 `protobuf:"varint,2,opt,name=FollowerCount,proto3" json:"FollowerCount,omitempty"`
	FollowingCount uint64                 `protobuf:"varint,3,opt,name=FollowingCount,proto3" json:"FollowingCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostFollowCountResponse) Reset() {
	*x = PostFollowCountResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFollowCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFollowCountResponse) ProtoMessage() {}

func (x *PostFollowCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFollowCountResponse.ProtoReflect.Descriptor instead.
func (*PostFollowCountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{1}
}

func (x *PostFollowCountResponse) GetPostCount() uint64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *PostFollowCountResponse) GetFollowerCount() uint64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *PostFollowCountResponse) GetFollowingCount() uint64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

type FetchCommentsOfCommentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PostId          uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	ParentCommentId uint64                 `protobuf:"varint,2,opt,name=ParentCommentId,proto3" json:"ParentCommentId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchCommentsOfCommentRequest) Reset() {
	*x = FetchCommentsOfCommentRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsOfCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsOfCommentRequest) ProtoMessage() {}

func (x *FetchCommentsOfCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsOfCommentRequest.ProtoReflect.Descriptor instead.
func (*FetchCommentsOfCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{2}
}

func (x *FetchCommentsOfCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FetchCommentsOfCommentRequest) GetParentCommentId() uint64 {
	if x != nil {
		return x.ParentCommentId
	}
	return 0
}

type FetchCommentsOfCommentResposne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=Comments,proto3" json:"Comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommentsOfCommentResposne) Reset() {
	*x = FetchCommentsOfCommentResposne{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsOfCommentResposne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsOfCommentResposne) ProtoMessage() {}

func (x *FetchCommentsOfCommentResposne) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsOfCommentResposne.ProtoReflect.Descriptor instead.
func (*FetchCommentsOfCommentResposne) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{3}
}

func (x *FetchCommentsOfCommentResposne) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type FetchCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommentsRequest) Reset() {
	*x = FetchCommentsRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsRequest) ProtoMessage() {}

func (x *FetchCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsRequest.ProtoReflect.Descriptor instead.
func (*FetchCommentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{4}
}

func (x *FetchCommentsRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CommentText   string                 `protobuf:"bytes,2,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{5}
}

func (x *Comment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

type FetchCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=Comments,proto3" json:"Comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommentsResponse) Reset() {
	*x = FetchCommentsResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsResponse) ProtoMessage() {}

func (x *FetchCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsResponse.ProtoReflect.Descriptor instead.
func (*FetchCommentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{6}
}

func (x *FetchCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type UnfollowRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UnfollowingUserId uint64                 `protobuf:"varint,2,opt,name=UnfollowingUserId,proto3" json:"UnfollowingUserId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{7}
}

func (x *UnfollowRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfollowRequest) GetUnfollowingUserId() uint64 {
	if x != nil {
		return x.UnfollowingUserId
	}
	return 0
}

type UnfollowResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UnfollowingUserId uint64                 `protobuf:"varint,1,opt,name=UnfollowingUserId,proto3" json:"UnfollowingUserId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{8}
}

func (x *UnfollowResponse) GetUnfollowingUserId() uint64 {
	if x != nil {
		return x.UnfollowingUserId
	}
	return 0
}

type FollowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FollowingUserId uint64                 `protobuf:"varint,2,opt,name=FollowingUserId,proto3" json:"FollowingUserId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{9}
}

func (x *FollowRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetFollowingUserId() uint64 {
	if x != nil {
		return x.FollowingUserId
	}
	return 0
}

type FollowResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FollowingUserId uint64                 `protobuf:"varint,1,opt,name=FollowingUserId,proto3" json:"FollowingUserId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{10}
}

func (x *FollowResponse) GetFollowingUserId() uint64 {
	if x != nil {
		return x.FollowingUserId
	}
	return 0
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentId     uint64                 `protobuf:"varint,3,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeleteCommentRequest) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type EditCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentId     uint64                 `protobuf:"varint,3,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	CommentText   string                 `protobuf:"bytes,4,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentRequest) Reset() {
	*x = EditCommentRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentRequest) ProtoMessage() {}

func (x *EditCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentRequest.ProtoReflect.Descriptor instead.
func (*EditCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{13}
}

func (x *EditCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *EditCommentRequest) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *EditCommentRequest) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

type EditCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	CommentText   string                 `protobuf:"bytes,2,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentResponse) Reset() {
	*x = EditCommentResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentResponse) ProtoMessage() {}

func (x *EditCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentResponse.ProtoReflect.Descriptor instead.
func (*EditCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{14}
}

func (x *EditCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *EditCommentResponse) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

type AddCommentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId          uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentText     string                 `protobuf:"bytes,3,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	ParentCommentId *uint64                `protobuf:"varint,4,opt,name=ParentCommentId,proto3,oneof" json:"ParentCommentId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{15}
}

func (x *AddCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddCommentRequest) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *AddCommentRequest) GetParentCommentId() uint64 {
	if x != nil && x.ParentCommentId != nil {
		return *x.ParentCommentId
	}
	return 0
}

type AddCommentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId          uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentText     string                 `protobuf:"bytes,3,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	ParentCommentId *uint64                `protobuf:"varint,4,opt,name=ParentCommentId,proto3,oneof" json:"ParentCommentId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{16}
}

func (x *AddCommentResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddCommentResponse) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *AddCommentResponse) GetParentCommentId() uint64 {
	if x != nil && x.ParentCommentId != nil {
		return *x.ParentCommentId
	}
	return 0
}

type UnlikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostRequest) Reset() {
	*x = UnlikePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostRequest) ProtoMessage() {}

func (x *UnlikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostRequest.ProtoReflect.Descriptor instead.
func (*UnlikePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{17}
}

func (x *UnlikePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikePostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UnlikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostResponse) Reset() {
	*x = UnlikePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostResponse) ProtoMessage() {}

func (x *UnlikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostResponse.ProtoReflect.Descriptor instead.
func (*UnlikePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{18}
}

func (x *UnlikePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{19}
}

func (x *LikePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikePostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type LikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{20}
}

func (x *LikePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{21}
}

func (x *DeletePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeletePostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{22}
}

func (x *DeletePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type EditPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=Caption,proto3" json:"Caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPostRequest) Reset() {
	*x = EditPostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPostRequest) ProtoMessage() {}

func (x *EditPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPostRequest.ProtoReflect.Descriptor instead.
func (*EditPostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{23}
}

func (x *EditPostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditPostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *EditPostRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type EditPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caption       string                 `protobuf:"bytes,1,opt,name=Caption,proto3" json:"Caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPostResponse) Reset() {
	*x = EditPostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPostResponse) ProtoMessage() {}

func (x *EditPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPostResponse.ProtoReflect.Descriptor instead.
func (*EditPostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{24}
}

func (x *EditPostResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=Caption,proto3" json:"Caption,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{25}
}

func (x *CreatePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *CreatePostRequest) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{26}
}

func (x *CreatePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

var File_pkg_pb_post_relation_proto protoreflect.FileDescriptor

const file_pkg_pb_post_relation_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/pb/post_relation.proto\x12\rpost_relation\"0\n" +
	"\x16PostFollowCountRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"\x85\x01\n" +
	"\x17PostFollowCountResponse\x12\x1c\n" +
	"\tPostCount\x18\x01 \x01(\x04R\tPostCount\x12$\n" +
	"\rFollowerCount\x18\x02 \x01(\x04R\rFollowerCount\x12&\n" +
	"\x0eFollowingCount\x18\x03 \x01(\x04R\x0eFollowingCount\"a\n" +
	"\x1dFetchCommentsOfCommentRequest\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\x12(\n" +
	"\x0fParentCommentId\x18\x02 \x01(\x04R\x0fParentCommentId\"T\n" +
	"\x1eFetchCommentsOfCommentResposne\x122\n" +
	"\bComments\x18\x01 \x03(\v2\x16.post_relation.CommentR\bComments\".\n" +
	"\x14FetchCommentsRequest\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\";\n" +
	"\aComment\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12 \n" +
	"\vCommentText\x18\x02 \x01(\tR\vCommentText\"K\n" +
	"\x15FetchCommentsResponse\x122\n" +
	"\bComments\x18\x01 \x03(\v2\x16.post_relation.CommentR\bComments\"W\n" +
	"\x0fUnfollowRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12,\n" +
	"\x11UnfollowingUserId\x18\x02 \x01(\x04R\x11UnfollowingUserId\"@\n" +
	"\x10UnfollowResponse\x12,\n" +
	"\x11UnfollowingUserId\x18\x01 \x01(\x04R\x11UnfollowingUserId\"Q\n" +
	"\rFollowRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12(\n" +
	"\x0fFollowingUserId\x18\x02 \x01(\x04R\x0fFollowingUserId\":\n" +
	"\x0eFollowResponse\x12(\n" +
	"\x0fFollowingUserId\x18\x01 \x01(\x04R\x0fFollowingUserId\"d\n" +
	"\x14DeleteCommentRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12\x1c\n" +
	"\tCommentId\x18\x03 \x01(\x04R\tCommentId\"5\n" +
	"\x15DeleteCommentResponse\x12\x1c\n" +
	"\tCommentId\x18\x01 \x01(\x04R\tCommentId\"\x84\x01\n" +
	"\x12EditCommentRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12\x1c\n" +
	"\tCommentId\x18\x03 \x01(\x04R\tCommentId\x12 \n" +
	"\vCommentText\x18\x04 \x01(\tR\vCommentText\"U\n" +
	"\x13EditCommentResponse\x12\x1c\n" +
	"\tCommentId\x18\x01 \x01(\x04R\tCommentId\x12 \n" +
	"\vCommentText\x18\x02 \x01(\tR\vCommentText\"\xa8\x01\n" +
	"\x11AddCommentRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12 \n" +
	"\vCommentText\x18\x03 \x01(\tR\vCommentText\x12-\n" +
	"\x0fParentCommentId\x18\x04 \x01(\x04H\x00R\x0fParentCommentId\x88\x01\x01B\x12\n" +
	"\x10_ParentCommentId\"\xa9\x01\n" +
	"\x12AddCommentResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12 \n" +
	"\vCommentText\x18\x03 \x01(\tR\vCommentText\x12-\n" +
	"\x0fParentCommentId\x18\x04 \x01(\x04H\x00R\x0fParentCommentId\x88\x01\x01B\x12\n" +
	"\x10_ParentCommentId\"C\n" +
	"\x11UnlikePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\",\n" +
	"\x12UnlikePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\"A\n" +
	"\x0fLikePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\"*\n" +
	"\x10LikePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\"C\n" +
	"\x11DeletePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\",\n" +
	"\x12DeletePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\"[\n" +
	"\x0fEditPostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12\x18\n" +
	"\aCaption\x18\x03 \x01(\tR\aCaption\",\n" +
	"\x10EditPostResponse\x12\x18\n" +
	"\aCaption\x18\x01 \x01(\tR\aCaption\"d\n" +
	"\x11CreatePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aCaption\x18\x02 \x01(\tR\aCaption\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\",\n" +
	"\x12CreatePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId2\xf6\b\n" +
	"\x13PostRelationService\x12Q\n" +
	"\n" +
	"CreatePost\x12 .post_relation.CreatePostRequest\x1a!.post_relation.CreatePostResponse\x12K\n" +
	"\bEditPost\x12\x1e.post_relation.EditPostRequest\x1a\x1f.post_relation.EditPostResponse\x12Q\n" +
	"\n" +
	"DeletePost\x12 .post_relation.DeletePostRequest\x1a!.post_relation.DeletePostResponse\x12K\n" +
	"\bLikePost\x12\x1e.post_relation.LikePostRequest\x1a\x1f.post_relation.LikePostResponse\x12Q\n" +
	"\n" +
	"UnlikePost\x12 .post_relation.UnlikePostRequest\x1a!.post_relation.UnlikePostResponse\x12Q\n" +
	"\n" +
	"AddComment\x12 .post_relation.AddCommentRequest\x1a!.post_relation.AddCommentResponse\x12Z\n" +
	"\rFetchComments\x12#.post_relation.FetchCommentsRequest\x1a$.post_relation.FetchCommentsResponse\x12T\n" +
	"\vEditComment\x12!.post_relation.EditCommentRequest\x1a\".post_relation.EditCommentResponse\x12Z\n" +
	"\rDeleteComment\x12#.post_relation.DeleteCommentRequest\x1a$.post_relation.DeleteCommentResponse\x12u\n" +
	"\x16FetchCommentsOfComment\x12,.post_relation.FetchCommentsOfCommentRequest\x1a-.post_relation.FetchCommentsOfCommentResposne\x12E\n" +
	"\x06Follow\x12\x1c.post_relation.FollowRequest\x1a\x1d.post_relation.FollowResponse\x12K\n" +
	"\bUnfollow\x12\x1e.post_relation.UnfollowRequest\x1a\x1f.post_relation.UnfollowResponse\x12`\n" +
	"\x0fPostFollowCount\x12%.post_relation.PostFollowCountRequest\x1a&.post_relation.PostFollowCountResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_post_relation_proto_rawDescOnce sync.Once
	file_pkg_pb_post_relation_proto_rawDescData []byte
)

func file_pkg_pb_post_relation_proto_rawDescGZIP() []byte {
	file_pkg_pb_post_relation_proto_rawDescOnce.Do(func() {
		file_pkg_pb_post_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_post_relation_proto_rawDesc), len(file_pkg_pb_post_relation_proto_rawDesc)))
	})
	return file_pkg_pb_post_relation_proto_rawDescData
}

var file_pkg_pb_post_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pkg_pb_post_relation_proto_goTypes = []any{
	(*PostFollowCountRequest)(nil),         // 0: post_relation.PostFollowCountRequest
	(*PostFollowCountResponse)(nil),        // 1: post_relation.PostFollowCountResponse
	(*FetchCommentsOfCommentRequest)(nil),  // 2: post_relation.FetchCommentsOfCommentRequest
	(*FetchCommentsOfCommentResposne)(nil), // 3: post_relation.FetchCommentsOfCommentResposne
	(*FetchCommentsRequest)(nil),           // 4: post_relation.FetchCommentsRequest
	(*Comment)(nil),                        // 5: post_relation.Comment
	(*FetchCommentsResponse)(nil),          // 6: post_relation.FetchCommentsResponse
	(*UnfollowRequest)(nil),                // 7: post_relation.UnfollowRequest
	(*UnfollowResponse)(nil),               // 8: post_relation.UnfollowResponse
	(*FollowRequest)(nil),                  // 9: post_relation.FollowRequest
	(*FollowResponse)(nil),                 // 10: post_relation.FollowResponse
	(*DeleteCommentRequest)(nil),           // 11: post_relation.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),          // 12: post_relation.DeleteCommentResponse
	(*EditCommentRequest)(nil),             // 13: post_relation.EditCommentRequest
	(*EditCommentResponse)(nil),            // 14: post_relation.EditCommentResponse
	(*AddCommentRequest)(nil),              // 15: post_relation.AddCommentRequest
	(*AddCommentResponse)(nil),             // 16: post_relation.AddCommentResponse
	(*UnlikePostRequest)(nil),              // 17: post_relation.UnlikePostRequest
	(*UnlikePostResponse)(nil),             // 18: post_relation.UnlikePostResponse
	(*LikePostRequest)(nil),                // 19: post_relation.LikePostRequest
	(*LikePostResponse)(nil),               // 20: post_relation.LikePostResponse
	(*DeletePostRequest)(nil),              // 21: post_relation.DeletePostRequest
	(*DeletePostResponse)(nil),             // 22: post_relation.DeletePostResponse
	(*EditPostRequest)(nil),                // 23: post_relation.EditPostRequest
	(*EditPostResponse)(nil),               // 24: post_relation.EditPostResponse
	(*CreatePostRequest)(nil),              // 25: post_relation.CreatePostRequest
	(*CreatePostResponse)(nil),             // 26: post_relation.CreatePostResponse
}
var file_pkg_pb_post_relation_proto_depIdxs = []int32{
	5,  // 0: post_relation.FetchCommentsOfCommentResposne.Comments:type_name -> post_relation.Comment
	5,  // 1: post_relation.FetchCommentsResponse.Comments:type_name -> post_relation.Comment
	25, // 2: post_relation.PostRelationService.CreatePost:input_type -> post_relation.CreatePostRequest
	23, // 3: post_relation.PostRelationService.EditPost:input_type -> post_relation.EditPostRequest
	21, // 4: post_relation.PostRelationService.DeletePost:input_type -> post_relation.DeletePostRequest
	19, // 5: post_relation.PostRelationService.LikePost:input_type -> post_relation.LikePostRequest
	17, // 6: post_relation.PostRelationService.UnlikePost:input_type -> post_relation.UnlikePostRequest
	15, // 7: post_relation.PostRelationService.AddComment:input_type -> post_relation.AddCommentRequest
	4,  // 8: post_relation.PostRelationService.FetchComments:input_type -> post_relation.FetchCommentsRequest
	13, // 9: post_relation.PostRelationService.EditComment:input_type -> post_relation.EditCommentRequest
	11, // 10: post_relation.PostRelationService.DeleteComment:input_type -> post_relation.DeleteCommentRequest
	2,  // 11: post_relation.PostRelationService.FetchCommentsOfComment:input_type -> post_relation.FetchCommentsOfCommentRequest
	9,  // 12: post_relation.PostRelationService.Follow:input_type -> post_relation.FollowRequest
	7,  // 13: post_relation.PostRelationService.Unfollow:input_type -> post_relation.UnfollowRequest
	0,  // 14: post_relation.PostRelationService.PostFollowCount:input_type -> post_relation.PostFollowCountRequest
	26, // 15: post_relation.PostRelationService.CreatePost:output_type -> post_relation.CreatePostResponse
	24, // 16: post_relation.PostRelationService.EditPost:output_type -> post_relation.EditPostResponse
	22, // 17: post_relation.PostRelationService.DeletePost:output_type -> post_relation.DeletePostResponse
	20, // 18: post_relation.PostRelationService.LikePost:output_type -> post_relation.LikePostResponse
	18, // 19: post_relation.PostRelationService.UnlikePost:output_type -> post_relation.UnlikePostResponse
	16, // 20: post_relation.PostRelationService.AddComment:output_type -> post_relation.AddCommentResponse
	6,  // 21: post_relation.PostRelationService.FetchComments:output_type -> post_relation.FetchCommentsResponse
	14, // 22: post_relation.PostRelationService.EditComment:output_type -> post_relation.EditCommentResponse
	12, // 23: post_relation.PostRelationService.DeleteComment:output_type -> post_relation.DeleteCommentResponse
	3,  // 24: post_relation.PostRelationService.FetchCommentsOfComment:output_type -> post_relation.FetchCommentsOfCommentResposne
	10, // 25: post_relation.PostRelationService.Follow:output_type -> post_relation.FollowResponse
	8,  // 26: post_relation.PostRelationService.Unfollow:output_type -> post_relation.UnfollowResponse
	1,  // 27: post_relation.PostRelationService.PostFollowCount:output_type -> post_relation.PostFollowCountResponse
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_post_relation_proto_init() }
func file_pkg_pb_post_relation_proto_init() {
	if File_pkg_pb_post_relation_proto != nil {
		return
	}
	file_pkg_pb_post_relation_proto_msgTypes[15].OneofWrappers = []any{}
	file_pkg_pb_post_relation_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_post_relation_proto_rawDesc), len(file_pkg_pb_post_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_post_relation_proto_goTypes,
		DependencyIndexes: file_pkg_pb_post_relation_proto_depIdxs,
		MessageInfos:      file_pkg_pb_post_relation_proto_msgTypes,
	}.Build()
	File_pkg_pb_post_relation_proto = out.File
	file_pkg_pb_post_relation_proto_goTypes = nil
	file_pkg_pb_post_relation_proto_depIdxs = nil
}
