// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/pb/post_relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PanicInPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanicInPostReq) Reset() {
	*x = PanicInPostReq{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanicInPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanicInPostReq) ProtoMessage() {}

func (x *PanicInPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanicInPostReq.ProtoReflect.Descriptor instead.
func (*PanicInPostReq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{0}
}

type PanicInPostRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanicInPostRes) Reset() {
	*x = PanicInPostRes{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanicInPostRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanicInPostRes) ProtoMessage() {}

func (x *PanicInPostRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanicInPostRes.ProtoReflect.Descriptor instead.
func (*PanicInPostRes) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{1}
}

type InsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserRequest) Reset() {
	*x = InsertUserRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserRequest) ProtoMessage() {}

func (x *InsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserRequest.ProtoReflect.Descriptor instead.
func (*InsertUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{2}
}

func (x *InsertUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{3}
}

type FetchGlobalNewsFeedRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Limit  int64                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// float LastScore=3;
	Offset        int64 `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchGlobalNewsFeedRequest) Reset() {
	*x = FetchGlobalNewsFeedRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchGlobalNewsFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchGlobalNewsFeedRequest) ProtoMessage() {}

func (x *FetchGlobalNewsFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchGlobalNewsFeedRequest.ProtoReflect.Descriptor instead.
func (*FetchGlobalNewsFeedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{4}
}

func (x *FetchGlobalNewsFeedRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FetchGlobalNewsFeedRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchGlobalNewsFeedRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PostUserDataWithTrendingScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Caption       string                 `protobuf:"bytes,5,opt,name=Caption,proto3" json:"Caption,omitempty"`
	PostStatus    string                 `protobuf:"bytes,6,opt,name=PostStatus,proto3" json:"PostStatus,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,7,rep,name=MediaUrls,proto3" json:"MediaUrls,omitempty"`
	LikesCount    uint64                 `protobuf:"varint,8,opt,name=LikesCount,proto3" json:"LikesCount,omitempty"`
	CommentsCount uint64                 `protobuf:"varint,9,opt,name=CommentsCount,proto3" json:"CommentsCount,omitempty"`
	PostAge       string                 `protobuf:"bytes,10,opt,name=PostAge,proto3" json:"PostAge,omitempty"`
	IsLiked       bool                   `protobuf:"varint,11,opt,name=IsLiked,proto3" json:"IsLiked,omitempty"`
	TrendingScore float32                `protobuf:"fixed32,12,opt,name=TrendingScore,proto3" json:"TrendingScore,omitempty"`
	UserMetaData  *UserMetaData          `protobuf:"bytes,13,opt,name=userMetaData,proto3" json:"userMetaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserDataWithTrendingScore) Reset() {
	*x = PostUserDataWithTrendingScore{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserDataWithTrendingScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserDataWithTrendingScore) ProtoMessage() {}

func (x *PostUserDataWithTrendingScore) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserDataWithTrendingScore.ProtoReflect.Descriptor instead.
func (*PostUserDataWithTrendingScore) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{5}
}

func (x *PostUserDataWithTrendingScore) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostUserDataWithTrendingScore) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostUserDataWithTrendingScore) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PostUserDataWithTrendingScore) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostUserDataWithTrendingScore) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *PostUserDataWithTrendingScore) GetPostStatus() string {
	if x != nil {
		return x.PostStatus
	}
	return ""
}

func (x *PostUserDataWithTrendingScore) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *PostUserDataWithTrendingScore) GetLikesCount() uint64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *PostUserDataWithTrendingScore) GetCommentsCount() uint64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *PostUserDataWithTrendingScore) GetPostAge() string {
	if x != nil {
		return x.PostAge
	}
	return ""
}

func (x *PostUserDataWithTrendingScore) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *PostUserDataWithTrendingScore) GetTrendingScore() float32 {
	if x != nil {
		return x.TrendingScore
	}
	return 0
}

func (x *PostUserDataWithTrendingScore) GetUserMetaData() *UserMetaData {
	if x != nil {
		return x.UserMetaData
	}
	return nil
}

type FetchGlobalNewsFeedResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	PostUserData  []*PostUserDataWithTrendingScore `protobuf:"bytes,1,rep,name=postUserData,proto3" json:"postUserData,omitempty"`
	NextCursor    float32                          `protobuf:"fixed32,2,opt,name=NextCursor,proto3" json:"NextCursor,omitempty"`
	HasMore       bool                             `protobuf:"varint,3,opt,name=HasMore,proto3" json:"HasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchGlobalNewsFeedResponse) Reset() {
	*x = FetchGlobalNewsFeedResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchGlobalNewsFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchGlobalNewsFeedResponse) ProtoMessage() {}

func (x *FetchGlobalNewsFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchGlobalNewsFeedResponse.ProtoReflect.Descriptor instead.
func (*FetchGlobalNewsFeedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{6}
}

func (x *FetchGlobalNewsFeedResponse) GetPostUserData() []*PostUserDataWithTrendingScore {
	if x != nil {
		return x.PostUserData
	}
	return nil
}

func (x *FetchGlobalNewsFeedResponse) GetNextCursor() float32 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *FetchGlobalNewsFeedResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type FetchNewsFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	LastId        uint64                 `protobuf:"varint,3,opt,name=LastId,proto3" json:"LastId,omitempty"`
	PullToRefresh bool                   `protobuf:"varint,4,opt,name=PullToRefresh,proto3" json:"PullToRefresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchNewsFeedRequest) Reset() {
	*x = FetchNewsFeedRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNewsFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNewsFeedRequest) ProtoMessage() {}

func (x *FetchNewsFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNewsFeedRequest.ProtoReflect.Descriptor instead.
func (*FetchNewsFeedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{7}
}

func (x *FetchNewsFeedRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FetchNewsFeedRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchNewsFeedRequest) GetLastId() uint64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *FetchNewsFeedRequest) GetPullToRefresh() bool {
	if x != nil {
		return x.PullToRefresh
	}
	return false
}

type PostUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Caption       string                 `protobuf:"bytes,5,opt,name=Caption,proto3" json:"Caption,omitempty"`
	PostStatus    string                 `protobuf:"bytes,6,opt,name=PostStatus,proto3" json:"PostStatus,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,7,rep,name=MediaUrls,proto3" json:"MediaUrls,omitempty"`
	LikesCount    uint64                 `protobuf:"varint,8,opt,name=LikesCount,proto3" json:"LikesCount,omitempty"`
	CommentsCount uint64                 `protobuf:"varint,9,opt,name=CommentsCount,proto3" json:"CommentsCount,omitempty"`
	PostAge       string                 `protobuf:"bytes,10,opt,name=PostAge,proto3" json:"PostAge,omitempty"`
	IsLiked       bool                   `protobuf:"varint,11,opt,name=IsLiked,proto3" json:"IsLiked,omitempty"`
	UserMetaData  *UserMetaData          `protobuf:"bytes,12,opt,name=userMetaData,proto3" json:"userMetaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserData) Reset() {
	*x = PostUserData{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserData) ProtoMessage() {}

func (x *PostUserData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserData.ProtoReflect.Descriptor instead.
func (*PostUserData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{8}
}

func (x *PostUserData) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostUserData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostUserData) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PostUserData) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostUserData) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *PostUserData) GetPostStatus() string {
	if x != nil {
		return x.PostStatus
	}
	return ""
}

func (x *PostUserData) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *PostUserData) GetLikesCount() uint64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *PostUserData) GetCommentsCount() uint64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *PostUserData) GetPostAge() string {
	if x != nil {
		return x.PostAge
	}
	return ""
}

func (x *PostUserData) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *PostUserData) GetUserMetaData() *UserMetaData {
	if x != nil {
		return x.UserMetaData
	}
	return nil
}

type FetchNewsFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUserData  []*PostUserData        `protobuf:"bytes,1,rep,name=postUserData,proto3" json:"postUserData,omitempty"`
	NextCursor    uint64                 `protobuf:"varint,2,opt,name=NextCursor,proto3" json:"NextCursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=HasMore,proto3" json:"HasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchNewsFeedResponse) Reset() {
	*x = FetchNewsFeedResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNewsFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNewsFeedResponse) ProtoMessage() {}

func (x *FetchNewsFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNewsFeedResponse.ProtoReflect.Descriptor instead.
func (*FetchNewsFeedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{9}
}

func (x *FetchNewsFeedResponse) GetPostUserData() []*PostUserData {
	if x != nil {
		return x.PostUserData
	}
	return nil
}

func (x *FetchNewsFeedResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *FetchNewsFeedResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type FetchFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFollowingRequest) Reset() {
	*x = FetchFollowingRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFollowingRequest) ProtoMessage() {}

func (x *FetchFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFollowingRequest.ProtoReflect.Descriptor instead.
func (*FetchFollowingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{10}
}

func (x *FetchFollowingRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FetchFollowingRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchFollowingRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FetchFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserMetaData  []*UserMetaData        `protobuf:"bytes,1,rep,name=userMetaData,proto3" json:"userMetaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFollowingResponse) Reset() {
	*x = FetchFollowingResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFollowingResponse) ProtoMessage() {}

func (x *FetchFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFollowingResponse.ProtoReflect.Descriptor instead.
func (*FetchFollowingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{11}
}

func (x *FetchFollowingResponse) GetUserMetaData() []*UserMetaData {
	if x != nil {
		return x.UserMetaData
	}
	return nil
}

type FetchFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFollowersRequest) Reset() {
	*x = FetchFollowersRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFollowersRequest) ProtoMessage() {}

func (x *FetchFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFollowersRequest.ProtoReflect.Descriptor instead.
func (*FetchFollowersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{12}
}

func (x *FetchFollowersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FetchFollowersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchFollowersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FetchFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserMetaData  []*UserMetaData        `protobuf:"bytes,1,rep,name=userMetaData,proto3" json:"userMetaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFollowersResponse) Reset() {
	*x = FetchFollowersResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFollowersResponse) ProtoMessage() {}

func (x *FetchFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFollowersResponse.ProtoReflect.Descriptor instead.
func (*FetchFollowersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{13}
}

func (x *FetchFollowersResponse) GetUserMetaData() []*UserMetaData {
	if x != nil {
		return x.UserMetaData
	}
	return nil
}

type FetchAllPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=CurrentUserId,proto3" json:"CurrentUserId,omitempty"`
	TargetUserId  uint64                 `protobuf:"varint,2,opt,name=TargetUserId,proto3" json:"TargetUserId,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAllPostsRequest) Reset() {
	*x = FetchAllPostsRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAllPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllPostsRequest) ProtoMessage() {}

func (x *FetchAllPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllPostsRequest.ProtoReflect.Descriptor instead.
func (*FetchAllPostsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{14}
}

func (x *FetchAllPostsRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *FetchAllPostsRequest) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *FetchAllPostsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchAllPostsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FetchAllPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAllPostsResponse) Reset() {
	*x = FetchAllPostsResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllPostsResponse) ProtoMessage() {}

func (x *FetchAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllPostsResponse.ProtoReflect.Descriptor instead.
func (*FetchAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{15}
}

func (x *FetchAllPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Caption       string                 `protobuf:"bytes,5,opt,name=Caption,proto3" json:"Caption,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,6,rep,name=MediaUrls,proto3" json:"MediaUrls,omitempty"`
	LikesCount    uint64                 `protobuf:"varint,7,opt,name=LikesCount,proto3" json:"LikesCount,omitempty"`
	CommentsCount uint64                 `protobuf:"varint,8,opt,name=CommentsCount,proto3" json:"CommentsCount,omitempty"`
	PostAge       string                 `protobuf:"bytes,9,opt,name=PostAge,proto3" json:"PostAge,omitempty"`
	Isliked       bool                   `protobuf:"varint,10,opt,name=Isliked,proto3" json:"Isliked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{16}
}

func (x *Post) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Post) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Post) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *Post) GetLikesCount() uint64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *Post) GetCommentsCount() uint64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *Post) GetPostAge() string {
	if x != nil {
		return x.PostAge
	}
	return ""
}

func (x *Post) GetIsliked() bool {
	if x != nil {
		return x.Isliked
	}
	return false
}

type PostFollowCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostFollowCountRequest) Reset() {
	*x = PostFollowCountRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFollowCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFollowCountRequest) ProtoMessage() {}

func (x *PostFollowCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFollowCountRequest.ProtoReflect.Descriptor instead.
func (*PostFollowCountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{17}
}

func (x *PostFollowCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PostFollowCountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PostCount      uint64                 `protobuf:"varint,1,opt,name=PostCount,proto3" json:"PostCount,omitempty"`
	FollowerCount  uint64                 `protobuf:"varint,2,opt,name=FollowerCount,proto3" json:"FollowerCount,omitempty"`
	FollowingCount uint64                 `protobuf:"varint,3,opt,name=FollowingCount,proto3" json:"FollowingCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostFollowCountResponse) Reset() {
	*x = PostFollowCountResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFollowCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFollowCountResponse) ProtoMessage() {}

func (x *PostFollowCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFollowCountResponse.ProtoReflect.Descriptor instead.
func (*PostFollowCountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{18}
}

func (x *PostFollowCountResponse) GetPostCount() uint64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *PostFollowCountResponse) GetFollowerCount() uint64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *PostFollowCountResponse) GetFollowingCount() uint64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

type FetchCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommentsRequest) Reset() {
	*x = FetchCommentsRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsRequest) ProtoMessage() {}

func (x *FetchCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsRequest.ProtoReflect.Descriptor instead.
func (*FetchCommentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{19}
}

func (x *FetchCommentsRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FetchCommentsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchCommentsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UserMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ProfileImgUrl string                 `protobuf:"bytes,4,opt,name=ProfileImgUrl,proto3" json:"ProfileImgUrl,omitempty"`
	BlueTick      bool                   `protobuf:"varint,5,opt,name=BlueTick,proto3" json:"BlueTick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMetaData) Reset() {
	*x = UserMetaData{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMetaData) ProtoMessage() {}

func (x *UserMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMetaData.ProtoReflect.Descriptor instead.
func (*UserMetaData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{20}
}

func (x *UserMetaData) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserMetaData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserMetaData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMetaData) GetProfileImgUrl() string {
	if x != nil {
		return x.ProfileImgUrl
	}
	return ""
}

func (x *UserMetaData) GetBlueTick() bool {
	if x != nil {
		return x.BlueTick
	}
	return false
}

type Comment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CommentText       string                 `protobuf:"bytes,2,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CommentAge        string                 `protobuf:"bytes,4,opt,name=CommentAge,proto3" json:"CommentAge,omitempty"`
	UserDetails       *UserMetaData          `protobuf:"bytes,5,opt,name=UserDetails,proto3" json:"UserDetails,omitempty"`
	ParentCommentId   *uint64                `protobuf:"varint,6,opt,name=ParentCommentId,proto3,oneof" json:"ParentCommentId,omitempty"`
	ChildCommentCount uint64                 `protobuf:"varint,7,opt,name=ChildCommentCount,proto3" json:"ChildCommentCount,omitempty"`
	ChildComment      []*Comment             `protobuf:"bytes,8,rep,name=ChildComment,proto3" json:"ChildComment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{21}
}

func (x *Comment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetCommentAge() string {
	if x != nil {
		return x.CommentAge
	}
	return ""
}

func (x *Comment) GetUserDetails() *UserMetaData {
	if x != nil {
		return x.UserDetails
	}
	return nil
}

func (x *Comment) GetParentCommentId() uint64 {
	if x != nil && x.ParentCommentId != nil {
		return *x.ParentCommentId
	}
	return 0
}

func (x *Comment) GetChildCommentCount() uint64 {
	if x != nil {
		return x.ChildCommentCount
	}
	return 0
}

func (x *Comment) GetChildComment() []*Comment {
	if x != nil {
		return x.ChildComment
	}
	return nil
}

type FetchCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=Comments,proto3" json:"Comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommentsResponse) Reset() {
	*x = FetchCommentsResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsResponse) ProtoMessage() {}

func (x *FetchCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsResponse.ProtoReflect.Descriptor instead.
func (*FetchCommentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{22}
}

func (x *FetchCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type UnfollowRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UnfollowingUserId uint64                 `protobuf:"varint,2,opt,name=UnfollowingUserId,proto3" json:"UnfollowingUserId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{23}
}

func (x *UnfollowRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfollowRequest) GetUnfollowingUserId() uint64 {
	if x != nil {
		return x.UnfollowingUserId
	}
	return 0
}

type UnfollowResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UnfollowingUserId uint64                 `protobuf:"varint,1,opt,name=UnfollowingUserId,proto3" json:"UnfollowingUserId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{24}
}

func (x *UnfollowResponse) GetUnfollowingUserId() uint64 {
	if x != nil {
		return x.UnfollowingUserId
	}
	return 0
}

type FollowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FollowingUserId uint64                 `protobuf:"varint,2,opt,name=FollowingUserId,proto3" json:"FollowingUserId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{25}
}

func (x *FollowRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetFollowingUserId() uint64 {
	if x != nil {
		return x.FollowingUserId
	}
	return 0
}

type FollowResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FollowingUserId uint64                 `protobuf:"varint,1,opt,name=FollowingUserId,proto3" json:"FollowingUserId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{26}
}

func (x *FollowResponse) GetFollowingUserId() uint64 {
	if x != nil {
		return x.FollowingUserId
	}
	return 0
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentId     uint64                 `protobuf:"varint,3,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeleteCommentRequest) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type EditCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentId     uint64                 `protobuf:"varint,3,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	CommentText   string                 `protobuf:"bytes,4,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentRequest) Reset() {
	*x = EditCommentRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentRequest) ProtoMessage() {}

func (x *EditCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentRequest.ProtoReflect.Descriptor instead.
func (*EditCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{29}
}

func (x *EditCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *EditCommentRequest) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *EditCommentRequest) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

type EditCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentId     uint64                 `protobuf:"varint,2,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	CommentText   string                 `protobuf:"bytes,3,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentResponse) Reset() {
	*x = EditCommentResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentResponse) ProtoMessage() {}

func (x *EditCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentResponse.ProtoReflect.Descriptor instead.
func (*EditCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{30}
}

func (x *EditCommentResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *EditCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *EditCommentResponse) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

type AddCommentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId          uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentText     string                 `protobuf:"bytes,3,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	ParentCommentId *uint64                `protobuf:"varint,4,opt,name=ParentCommentId,proto3,oneof" json:"ParentCommentId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{31}
}

func (x *AddCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddCommentRequest) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *AddCommentRequest) GetParentCommentId() uint64 {
	if x != nil && x.ParentCommentId != nil {
		return *x.ParentCommentId
	}
	return 0
}

type AddCommentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId          uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	CommentId       uint64                 `protobuf:"varint,3,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	CommentText     string                 `protobuf:"bytes,4,opt,name=CommentText,proto3" json:"CommentText,omitempty"`
	ParentCommentId *uint64                `protobuf:"varint,5,opt,name=ParentCommentId,proto3,oneof" json:"ParentCommentId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{32}
}

func (x *AddCommentResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *AddCommentResponse) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *AddCommentResponse) GetParentCommentId() uint64 {
	if x != nil && x.ParentCommentId != nil {
		return *x.ParentCommentId
	}
	return 0
}

type UnlikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostRequest) Reset() {
	*x = UnlikePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostRequest) ProtoMessage() {}

func (x *UnlikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostRequest.ProtoReflect.Descriptor instead.
func (*UnlikePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{33}
}

func (x *UnlikePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikePostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UnlikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostResponse) Reset() {
	*x = UnlikePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostResponse) ProtoMessage() {}

func (x *UnlikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostResponse.ProtoReflect.Descriptor instead.
func (*UnlikePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{34}
}

func (x *UnlikePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{35}
}

func (x *LikePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikePostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type LikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{36}
}

func (x *LikePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{37}
}

func (x *DeletePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeletePostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{38}
}

func (x *DeletePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type EditPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=Caption,proto3" json:"Caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPostRequest) Reset() {
	*x = EditPostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPostRequest) ProtoMessage() {}

func (x *EditPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPostRequest.ProtoReflect.Descriptor instead.
func (*EditPostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{39}
}

func (x *EditPostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditPostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *EditPostRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type EditPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caption       string                 `protobuf:"bytes,1,opt,name=Caption,proto3" json:"Caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPostResponse) Reset() {
	*x = EditPostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPostResponse) ProtoMessage() {}

func (x *EditPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPostResponse.ProtoReflect.Descriptor instead.
func (*EditPostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{40}
}

func (x *EditPostResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=Caption,proto3" json:"Caption,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{41}
}

func (x *CreatePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *CreatePostRequest) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{42}
}

func (x *CreatePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

var File_pkg_pb_post_relation_proto protoreflect.FileDescriptor

const file_pkg_pb_post_relation_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/pb/post_relation.proto\x12\rpost_relation\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0ePanicInPostReq\"\x10\n" +
	"\x0ePanicInPostRes\"+\n" +
	"\x11InsertUserRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"\a\n" +
	"\x05Empty\"b\n" +
	"\x1aFetchGlobalNewsFeedRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\x03R\x06Offset\"\xfc\x03\n" +
	"\x1dPostUserDataWithTrendingScore\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aCaption\x18\x05 \x01(\tR\aCaption\x12\x1e\n" +
	"\n" +
	"PostStatus\x18\x06 \x01(\tR\n" +
	"PostStatus\x12\x1c\n" +
	"\tMediaUrls\x18\a \x03(\tR\tMediaUrls\x12\x1e\n" +
	"\n" +
	"LikesCount\x18\b \x01(\x04R\n" +
	"LikesCount\x12$\n" +
	"\rCommentsCount\x18\t \x01(\x04R\rCommentsCount\x12\x18\n" +
	"\aPostAge\x18\n" +
	" \x01(\tR\aPostAge\x12\x18\n" +
	"\aIsLiked\x18\v \x01(\bR\aIsLiked\x12$\n" +
	"\rTrendingScore\x18\f \x01(\x02R\rTrendingScore\x12?\n" +
	"\fuserMetaData\x18\r \x01(\v2\x1b.post_relation.UserMetaDataR\fuserMetaData\"\xa9\x01\n" +
	"\x1bFetchGlobalNewsFeedResponse\x12P\n" +
	"\fpostUserData\x18\x01 \x03(\v2,.post_relation.PostUserDataWithTrendingScoreR\fpostUserData\x12\x1e\n" +
	"\n" +
	"NextCursor\x18\x02 \x01(\x02R\n" +
	"NextCursor\x12\x18\n" +
	"\aHasMore\x18\x03 \x01(\bR\aHasMore\"\x82\x01\n" +
	"\x14FetchNewsFeedRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06LastId\x18\x03 \x01(\x04R\x06LastId\x12$\n" +
	"\rPullToRefresh\x18\x04 \x01(\bR\rPullToRefresh\"\xc5\x03\n" +
	"\fPostUserData\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aCaption\x18\x05 \x01(\tR\aCaption\x12\x1e\n" +
	"\n" +
	"PostStatus\x18\x06 \x01(\tR\n" +
	"PostStatus\x12\x1c\n" +
	"\tMediaUrls\x18\a \x03(\tR\tMediaUrls\x12\x1e\n" +
	"\n" +
	"LikesCount\x18\b \x01(\x04R\n" +
	"LikesCount\x12$\n" +
	"\rCommentsCount\x18\t \x01(\x04R\rCommentsCount\x12\x18\n" +
	"\aPostAge\x18\n" +
	" \x01(\tR\aPostAge\x12\x18\n" +
	"\aIsLiked\x18\v \x01(\bR\aIsLiked\x12?\n" +
	"\fuserMetaData\x18\f \x01(\v2\x1b.post_relation.UserMetaDataR\fuserMetaData\"\x92\x01\n" +
	"\x15FetchNewsFeedResponse\x12?\n" +
	"\fpostUserData\x18\x01 \x03(\v2\x1b.post_relation.PostUserDataR\fpostUserData\x12\x1e\n" +
	"\n" +
	"NextCursor\x18\x02 \x01(\x04R\n" +
	"NextCursor\x12\x18\n" +
	"\aHasMore\x18\x03 \x01(\bR\aHasMore\"]\n" +
	"\x15FetchFollowingRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\x03R\x06Offset\"Y\n" +
	"\x16FetchFollowingResponse\x12?\n" +
	"\fuserMetaData\x18\x01 \x03(\v2\x1b.post_relation.UserMetaDataR\fuserMetaData\"]\n" +
	"\x15FetchFollowersRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\x03R\x06Offset\"Y\n" +
	"\x16FetchFollowersResponse\x12?\n" +
	"\fuserMetaData\x18\x01 \x03(\v2\x1b.post_relation.UserMetaDataR\fuserMetaData\"\x8e\x01\n" +
	"\x14FetchAllPostsRequest\x12$\n" +
	"\rCurrentUserId\x18\x01 \x01(\x04R\rCurrentUserId\x12\"\n" +
	"\fTargetUserId\x18\x02 \x01(\x04R\fTargetUserId\x12\x14\n" +
	"\x05Limit\x18\x03 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x04 \x01(\x03R\x06Offset\"B\n" +
	"\x15FetchAllPostsResponse\x12)\n" +
	"\x05posts\x18\x01 \x03(\v2\x13.post_relation.PostR\x05posts\"\xdc\x02\n" +
	"\x04Post\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aCaption\x18\x05 \x01(\tR\aCaption\x12\x1c\n" +
	"\tMediaUrls\x18\x06 \x03(\tR\tMediaUrls\x12\x1e\n" +
	"\n" +
	"LikesCount\x18\a \x01(\x04R\n" +
	"LikesCount\x12$\n" +
	"\rCommentsCount\x18\b \x01(\x04R\rCommentsCount\x12\x18\n" +
	"\aPostAge\x18\t \x01(\tR\aPostAge\x12\x18\n" +
	"\aIsliked\x18\n" +
	" \x01(\bR\aIsliked\"0\n" +
	"\x16PostFollowCountRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"\x85\x01\n" +
	"\x17PostFollowCountResponse\x12\x1c\n" +
	"\tPostCount\x18\x01 \x01(\x04R\tPostCount\x12$\n" +
	"\rFollowerCount\x18\x02 \x01(\x04R\rFollowerCount\x12&\n" +
	"\x0eFollowingCount\x18\x03 \x01(\x04R\x0eFollowingCount\"\\\n" +
	"\x14FetchCommentsRequest\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\x03R\x06Offset\"\x98\x01\n" +
	"\fUserMetaData\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12$\n" +
	"\rProfileImgUrl\x18\x04 \x01(\tR\rProfileImgUrl\x12\x1a\n" +
	"\bBlueTick\x18\x05 \x01(\bR\bBlueTick\"\x81\x03\n" +
	"\aComment\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12 \n" +
	"\vCommentText\x18\x02 \x01(\tR\vCommentText\x128\n" +
	"\tCreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x1e\n" +
	"\n" +
	"CommentAge\x18\x04 \x01(\tR\n" +
	"CommentAge\x12=\n" +
	"\vUserDetails\x18\x05 \x01(\v2\x1b.post_relation.UserMetaDataR\vUserDetails\x12-\n" +
	"\x0fParentCommentId\x18\x06 \x01(\x04H\x00R\x0fParentCommentId\x88\x01\x01\x12,\n" +
	"\x11ChildCommentCount\x18\a \x01(\x04R\x11ChildCommentCount\x12:\n" +
	"\fChildComment\x18\b \x03(\v2\x16.post_relation.CommentR\fChildCommentB\x12\n" +
	"\x10_ParentCommentId\"K\n" +
	"\x15FetchCommentsResponse\x122\n" +
	"\bComments\x18\x01 \x03(\v2\x16.post_relation.CommentR\bComments\"W\n" +
	"\x0fUnfollowRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12,\n" +
	"\x11UnfollowingUserId\x18\x02 \x01(\x04R\x11UnfollowingUserId\"@\n" +
	"\x10UnfollowResponse\x12,\n" +
	"\x11UnfollowingUserId\x18\x01 \x01(\x04R\x11UnfollowingUserId\"Q\n" +
	"\rFollowRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12(\n" +
	"\x0fFollowingUserId\x18\x02 \x01(\x04R\x0fFollowingUserId\":\n" +
	"\x0eFollowResponse\x12(\n" +
	"\x0fFollowingUserId\x18\x01 \x01(\x04R\x0fFollowingUserId\"d\n" +
	"\x14DeleteCommentRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12\x1c\n" +
	"\tCommentId\x18\x03 \x01(\x04R\tCommentId\"5\n" +
	"\x15DeleteCommentResponse\x12\x1c\n" +
	"\tCommentId\x18\x01 \x01(\x04R\tCommentId\"\x84\x01\n" +
	"\x12EditCommentRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12\x1c\n" +
	"\tCommentId\x18\x03 \x01(\x04R\tCommentId\x12 \n" +
	"\vCommentText\x18\x04 \x01(\tR\vCommentText\"m\n" +
	"\x13EditCommentResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\x12\x1c\n" +
	"\tCommentId\x18\x02 \x01(\x04R\tCommentId\x12 \n" +
	"\vCommentText\x18\x03 \x01(\tR\vCommentText\"\xa8\x01\n" +
	"\x11AddCommentRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12 \n" +
	"\vCommentText\x18\x03 \x01(\tR\vCommentText\x12-\n" +
	"\x0fParentCommentId\x18\x04 \x01(\x04H\x00R\x0fParentCommentId\x88\x01\x01B\x12\n" +
	"\x10_ParentCommentId\"\xc7\x01\n" +
	"\x12AddCommentResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12\x1c\n" +
	"\tCommentId\x18\x03 \x01(\x04R\tCommentId\x12 \n" +
	"\vCommentText\x18\x04 \x01(\tR\vCommentText\x12-\n" +
	"\x0fParentCommentId\x18\x05 \x01(\x04H\x00R\x0fParentCommentId\x88\x01\x01B\x12\n" +
	"\x10_ParentCommentId\"C\n" +
	"\x11UnlikePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\",\n" +
	"\x12UnlikePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\"A\n" +
	"\x0fLikePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\"*\n" +
	"\x10LikePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\"C\n" +
	"\x11DeletePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\",\n" +
	"\x12DeletePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId\"[\n" +
	"\x0fEditPostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x04R\x06PostId\x12\x18\n" +
	"\aCaption\x18\x03 \x01(\tR\aCaption\",\n" +
	"\x10EditPostResponse\x12\x18\n" +
	"\aCaption\x18\x01 \x01(\tR\aCaption\"d\n" +
	"\x11CreatePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aCaption\x18\x02 \x01(\tR\aCaption\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\",\n" +
	"\x12CreatePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId2\x85\r\n" +
	"\x13PostRelationService\x12S\n" +
	"\x19InsertUserIntoFollowCount\x12 .post_relation.InsertUserRequest\x1a\x14.post_relation.Empty\x12Q\n" +
	"\n" +
	"CreatePost\x12 .post_relation.CreatePostRequest\x1a!.post_relation.CreatePostResponse\x12Z\n" +
	"\rFetchAllPosts\x12#.post_relation.FetchAllPostsRequest\x1a$.post_relation.FetchAllPostsResponse\x12K\n" +
	"\bEditPost\x12\x1e.post_relation.EditPostRequest\x1a\x1f.post_relation.EditPostResponse\x12Q\n" +
	"\n" +
	"DeletePost\x12 .post_relation.DeletePostRequest\x1a!.post_relation.DeletePostResponse\x12K\n" +
	"\bLikePost\x12\x1e.post_relation.LikePostRequest\x1a\x1f.post_relation.LikePostResponse\x12Q\n" +
	"\n" +
	"UnlikePost\x12 .post_relation.UnlikePostRequest\x1a!.post_relation.UnlikePostResponse\x12Q\n" +
	"\n" +
	"AddComment\x12 .post_relation.AddCommentRequest\x1a!.post_relation.AddCommentResponse\x12Z\n" +
	"\rFetchComments\x12#.post_relation.FetchCommentsRequest\x1a$.post_relation.FetchCommentsResponse\x12T\n" +
	"\vEditComment\x12!.post_relation.EditCommentRequest\x1a\".post_relation.EditCommentResponse\x12Z\n" +
	"\rDeleteComment\x12#.post_relation.DeleteCommentRequest\x1a$.post_relation.DeleteCommentResponse\x12E\n" +
	"\x06Follow\x12\x1c.post_relation.FollowRequest\x1a\x1d.post_relation.FollowResponse\x12K\n" +
	"\bUnfollow\x12\x1e.post_relation.UnfollowRequest\x1a\x1f.post_relation.UnfollowResponse\x12]\n" +
	"\x0eFetchFollowers\x12$.post_relation.FetchFollowersRequest\x1a%.post_relation.FetchFollowersResponse\x12]\n" +
	"\x0eFetchFollowing\x12$.post_relation.FetchFollowingRequest\x1a%.post_relation.FetchFollowingResponse\x12`\n" +
	"\x0fPostFollowCount\x12%.post_relation.PostFollowCountRequest\x1a&.post_relation.PostFollowCountResponse\x12Z\n" +
	"\rFetchNewsFeed\x12#.post_relation.FetchNewsFeedRequest\x1a$.post_relation.FetchNewsFeedResponse\x12l\n" +
	"\x13FetchGlobalNewsFeed\x12).post_relation.FetchGlobalNewsFeedRequest\x1a*.post_relation.FetchGlobalNewsFeedResponse\x12K\n" +
	"\vPanicInPost\x12\x1d.post_relation.PanicInPostReq\x1a\x1d.post_relation.PanicInPostResB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_post_relation_proto_rawDescOnce sync.Once
	file_pkg_pb_post_relation_proto_rawDescData []byte
)

func file_pkg_pb_post_relation_proto_rawDescGZIP() []byte {
	file_pkg_pb_post_relation_proto_rawDescOnce.Do(func() {
		file_pkg_pb_post_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_post_relation_proto_rawDesc), len(file_pkg_pb_post_relation_proto_rawDesc)))
	})
	return file_pkg_pb_post_relation_proto_rawDescData
}

var file_pkg_pb_post_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_pkg_pb_post_relation_proto_goTypes = []any{
	(*PanicInPostReq)(nil),                // 0: post_relation.PanicInPostReq
	(*PanicInPostRes)(nil),                // 1: post_relation.PanicInPostRes
	(*InsertUserRequest)(nil),             // 2: post_relation.InsertUserRequest
	(*Empty)(nil),                         // 3: post_relation.Empty
	(*FetchGlobalNewsFeedRequest)(nil),    // 4: post_relation.FetchGlobalNewsFeedRequest
	(*PostUserDataWithTrendingScore)(nil), // 5: post_relation.PostUserDataWithTrendingScore
	(*FetchGlobalNewsFeedResponse)(nil),   // 6: post_relation.FetchGlobalNewsFeedResponse
	(*FetchNewsFeedRequest)(nil),          // 7: post_relation.FetchNewsFeedRequest
	(*PostUserData)(nil),                  // 8: post_relation.PostUserData
	(*FetchNewsFeedResponse)(nil),         // 9: post_relation.FetchNewsFeedResponse
	(*FetchFollowingRequest)(nil),         // 10: post_relation.FetchFollowingRequest
	(*FetchFollowingResponse)(nil),        // 11: post_relation.FetchFollowingResponse
	(*FetchFollowersRequest)(nil),         // 12: post_relation.FetchFollowersRequest
	(*FetchFollowersResponse)(nil),        // 13: post_relation.FetchFollowersResponse
	(*FetchAllPostsRequest)(nil),          // 14: post_relation.FetchAllPostsRequest
	(*FetchAllPostsResponse)(nil),         // 15: post_relation.FetchAllPostsResponse
	(*Post)(nil),                          // 16: post_relation.Post
	(*PostFollowCountRequest)(nil),        // 17: post_relation.PostFollowCountRequest
	(*PostFollowCountResponse)(nil),       // 18: post_relation.PostFollowCountResponse
	(*FetchCommentsRequest)(nil),          // 19: post_relation.FetchCommentsRequest
	(*UserMetaData)(nil),                  // 20: post_relation.UserMetaData
	(*Comment)(nil),                       // 21: post_relation.Comment
	(*FetchCommentsResponse)(nil),         // 22: post_relation.FetchCommentsResponse
	(*UnfollowRequest)(nil),               // 23: post_relation.UnfollowRequest
	(*UnfollowResponse)(nil),              // 24: post_relation.UnfollowResponse
	(*FollowRequest)(nil),                 // 25: post_relation.FollowRequest
	(*FollowResponse)(nil),                // 26: post_relation.FollowResponse
	(*DeleteCommentRequest)(nil),          // 27: post_relation.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),         // 28: post_relation.DeleteCommentResponse
	(*EditCommentRequest)(nil),            // 29: post_relation.EditCommentRequest
	(*EditCommentResponse)(nil),           // 30: post_relation.EditCommentResponse
	(*AddCommentRequest)(nil),             // 31: post_relation.AddCommentRequest
	(*AddCommentResponse)(nil),            // 32: post_relation.AddCommentResponse
	(*UnlikePostRequest)(nil),             // 33: post_relation.UnlikePostRequest
	(*UnlikePostResponse)(nil),            // 34: post_relation.UnlikePostResponse
	(*LikePostRequest)(nil),               // 35: post_relation.LikePostRequest
	(*LikePostResponse)(nil),              // 36: post_relation.LikePostResponse
	(*DeletePostRequest)(nil),             // 37: post_relation.DeletePostRequest
	(*DeletePostResponse)(nil),            // 38: post_relation.DeletePostResponse
	(*EditPostRequest)(nil),               // 39: post_relation.EditPostRequest
	(*EditPostResponse)(nil),              // 40: post_relation.EditPostResponse
	(*CreatePostRequest)(nil),             // 41: post_relation.CreatePostRequest
	(*CreatePostResponse)(nil),            // 42: post_relation.CreatePostResponse
	(*timestamppb.Timestamp)(nil),         // 43: google.protobuf.Timestamp
}
var file_pkg_pb_post_relation_proto_depIdxs = []int32{
	43, // 0: post_relation.PostUserDataWithTrendingScore.CreatedAt:type_name -> google.protobuf.Timestamp
	43, // 1: post_relation.PostUserDataWithTrendingScore.UpdatedAt:type_name -> google.protobuf.Timestamp
	20, // 2: post_relation.PostUserDataWithTrendingScore.userMetaData:type_name -> post_relation.UserMetaData
	5,  // 3: post_relation.FetchGlobalNewsFeedResponse.postUserData:type_name -> post_relation.PostUserDataWithTrendingScore
	43, // 4: post_relation.PostUserData.CreatedAt:type_name -> google.protobuf.Timestamp
	43, // 5: post_relation.PostUserData.UpdatedAt:type_name -> google.protobuf.Timestamp
	20, // 6: post_relation.PostUserData.userMetaData:type_name -> post_relation.UserMetaData
	8,  // 7: post_relation.FetchNewsFeedResponse.postUserData:type_name -> post_relation.PostUserData
	20, // 8: post_relation.FetchFollowingResponse.userMetaData:type_name -> post_relation.UserMetaData
	20, // 9: post_relation.FetchFollowersResponse.userMetaData:type_name -> post_relation.UserMetaData
	16, // 10: post_relation.FetchAllPostsResponse.posts:type_name -> post_relation.Post
	43, // 11: post_relation.Post.CreatedAt:type_name -> google.protobuf.Timestamp
	43, // 12: post_relation.Post.UpdatedAt:type_name -> google.protobuf.Timestamp
	43, // 13: post_relation.Comment.CreatedAt:type_name -> google.protobuf.Timestamp
	20, // 14: post_relation.Comment.UserDetails:type_name -> post_relation.UserMetaData
	21, // 15: post_relation.Comment.ChildComment:type_name -> post_relation.Comment
	21, // 16: post_relation.FetchCommentsResponse.Comments:type_name -> post_relation.Comment
	2,  // 17: post_relation.PostRelationService.InsertUserIntoFollowCount:input_type -> post_relation.InsertUserRequest
	41, // 18: post_relation.PostRelationService.CreatePost:input_type -> post_relation.CreatePostRequest
	14, // 19: post_relation.PostRelationService.FetchAllPosts:input_type -> post_relation.FetchAllPostsRequest
	39, // 20: post_relation.PostRelationService.EditPost:input_type -> post_relation.EditPostRequest
	37, // 21: post_relation.PostRelationService.DeletePost:input_type -> post_relation.DeletePostRequest
	35, // 22: post_relation.PostRelationService.LikePost:input_type -> post_relation.LikePostRequest
	33, // 23: post_relation.PostRelationService.UnlikePost:input_type -> post_relation.UnlikePostRequest
	31, // 24: post_relation.PostRelationService.AddComment:input_type -> post_relation.AddCommentRequest
	19, // 25: post_relation.PostRelationService.FetchComments:input_type -> post_relation.FetchCommentsRequest
	29, // 26: post_relation.PostRelationService.EditComment:input_type -> post_relation.EditCommentRequest
	27, // 27: post_relation.PostRelationService.DeleteComment:input_type -> post_relation.DeleteCommentRequest
	25, // 28: post_relation.PostRelationService.Follow:input_type -> post_relation.FollowRequest
	23, // 29: post_relation.PostRelationService.Unfollow:input_type -> post_relation.UnfollowRequest
	12, // 30: post_relation.PostRelationService.FetchFollowers:input_type -> post_relation.FetchFollowersRequest
	10, // 31: post_relation.PostRelationService.FetchFollowing:input_type -> post_relation.FetchFollowingRequest
	17, // 32: post_relation.PostRelationService.PostFollowCount:input_type -> post_relation.PostFollowCountRequest
	7,  // 33: post_relation.PostRelationService.FetchNewsFeed:input_type -> post_relation.FetchNewsFeedRequest
	4,  // 34: post_relation.PostRelationService.FetchGlobalNewsFeed:input_type -> post_relation.FetchGlobalNewsFeedRequest
	0,  // 35: post_relation.PostRelationService.PanicInPost:input_type -> post_relation.PanicInPostReq
	3,  // 36: post_relation.PostRelationService.InsertUserIntoFollowCount:output_type -> post_relation.Empty
	42, // 37: post_relation.PostRelationService.CreatePost:output_type -> post_relation.CreatePostResponse
	15, // 38: post_relation.PostRelationService.FetchAllPosts:output_type -> post_relation.FetchAllPostsResponse
	40, // 39: post_relation.PostRelationService.EditPost:output_type -> post_relation.EditPostResponse
	38, // 40: post_relation.PostRelationService.DeletePost:output_type -> post_relation.DeletePostResponse
	36, // 41: post_relation.PostRelationService.LikePost:output_type -> post_relation.LikePostResponse
	34, // 42: post_relation.PostRelationService.UnlikePost:output_type -> post_relation.UnlikePostResponse
	32, // 43: post_relation.PostRelationService.AddComment:output_type -> post_relation.AddCommentResponse
	22, // 44: post_relation.PostRelationService.FetchComments:output_type -> post_relation.FetchCommentsResponse
	30, // 45: post_relation.PostRelationService.EditComment:output_type -> post_relation.EditCommentResponse
	28, // 46: post_relation.PostRelationService.DeleteComment:output_type -> post_relation.DeleteCommentResponse
	26, // 47: post_relation.PostRelationService.Follow:output_type -> post_relation.FollowResponse
	24, // 48: post_relation.PostRelationService.Unfollow:output_type -> post_relation.UnfollowResponse
	13, // 49: post_relation.PostRelationService.FetchFollowers:output_type -> post_relation.FetchFollowersResponse
	11, // 50: post_relation.PostRelationService.FetchFollowing:output_type -> post_relation.FetchFollowingResponse
	18, // 51: post_relation.PostRelationService.PostFollowCount:output_type -> post_relation.PostFollowCountResponse
	9,  // 52: post_relation.PostRelationService.FetchNewsFeed:output_type -> post_relation.FetchNewsFeedResponse
	6,  // 53: post_relation.PostRelationService.FetchGlobalNewsFeed:output_type -> post_relation.FetchGlobalNewsFeedResponse
	1,  // 54: post_relation.PostRelationService.PanicInPost:output_type -> post_relation.PanicInPostRes
	36, // [36:55] is the sub-list for method output_type
	17, // [17:36] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pkg_pb_post_relation_proto_init() }
func file_pkg_pb_post_relation_proto_init() {
	if File_pkg_pb_post_relation_proto != nil {
		return
	}
	file_pkg_pb_post_relation_proto_msgTypes[21].OneofWrappers = []any{}
	file_pkg_pb_post_relation_proto_msgTypes[31].OneofWrappers = []any{}
	file_pkg_pb_post_relation_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_post_relation_proto_rawDesc), len(file_pkg_pb_post_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_post_relation_proto_goTypes,
		DependencyIndexes: file_pkg_pb_post_relation_proto_depIdxs,
		MessageInfos:      file_pkg_pb_post_relation_proto_msgTypes,
	}.Build()
	File_pkg_pb_post_relation_proto = out.File
	file_pkg_pb_post_relation_proto_goTypes = nil
	file_pkg_pb_post_relation_proto_depIdxs = nil
}
