package interfaces

import (
	"context"

	"github.com/Ansalps/Chattr_Api_Gateway/pkg/auth_subscription_svc/models/requestmodels"
	"github.com/Ansalps/Chattr_Api_Gateway/pkg/auth_subscription_svc/models/responsemodels"
)

type AuthSubscriptionClientInterface interface{
	AdminLogin(context.Context,requestmodels.AdminLoginRequest) (responsemodels.AdminLoginResponse,error)
	BlockUser(requestmodels.BlockUserRequest)(responsemodels.BlockUserResponse,error)
	UnblockUser(requestmodels.UnblockUserRequest)(responsemodels.UnblockUserResponse,error)
	GetAllUsers(requestmodels.GetAllUsersRequest,int)(responsemodels.GetAllUsersResponse,error)
	CreateSubscriptionPlan(requestmodels.CreateSubscriptionPlanRequest)(responsemodels.CreateSubscriptionPlanResponse,error)
	
	ActivateSubscriptionPlan(requestmodels.ActivateSubscriptionPlanRequest)(responsemodels.ActivateSubscriptionPlanResponse,error)
	DeactivateSubscriptionPlan(requestmodels.DeactivateSubscriptionPlanRequest)(responsemodels.DeactivateSubscriptionPlanResponse,error)
	GetAllSubscriptionPlans(requestmodels.GetAllSubscriptionPlansRequest,int)(responsemodels.GetAllSubscriptionPlansResponse,error)

	UserSignUp(ctx context.Context,user requestmodels.UserSignUpRequest)(responsemodels.UserSignupResponse,error)
	VerifyOtp(requestmodels.OtpRequest)(responsemodels.OtpVerificationResponse,error)
	ResendOtp(requestmodels.ResendOtpRequest)(responsemodels.ResendOtpResponse,error)
	AccessRegenerator(requestmodels.AccessRegeneratorRequest)(responsemodels.AccessRegeneratorResponse,error)
	ForgotPassword(requestmodels.ForgotPasswordRequest)(responsemodels.ForgetPassordResponse,error)
	ResetPassword(requestmodels.ResetPasswordRequest)(responsemodels.ResetPasswordResponse,error)
	UserLogin(requestmodels.UserLoginRequest)(responsemodels.UserLoginResponse,error)
	GetAllActiveSubscriptionPlans(requestmodels.GetAllActiveSubscriptionPlansRequest,int)(responsemodels.GetAllActiveSubscriptionPlansResponse,error)
	Subscribe(requestmodels.SubscribeRequest)(responsemodels.SubscribeResponse,error)
	VerifySubscriptionPayment(requestmodels.VerifySubscriptionPaymentRequest)(responsemodels.VerifySubscriptionPaymentResponse,error)
	Unsubscribe(requestmodels.UnsubscribeRequest)(responsemodels.UnsubscribeResponse,error)
	SetProfileImage(requestmodels.SetProfileImageRequest)(responsemodels.SetProfileImageResponse,error)

	GetProfileInformation(requestmodels.GetProfileInformationRequest)(responsemodels.GetProfileInformationResponse,error)

	WebhookSubsciptionCompleted(requestmodels.RazorpayEvent)(responsemodels.WebhookResponse,error)
}