// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/pb/post_relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserRequest) Reset() {
	*x = InsertUserRequest{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserRequest) ProtoMessage() {}

func (x *InsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserRequest.ProtoReflect.Descriptor instead.
func (*InsertUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{0}
}

func (x *InsertUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_pb_post_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_post_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_pb_post_relation_proto_rawDescGZIP(), []int{1}
}

var File_pkg_pb_post_relation_proto protoreflect.FileDescriptor

const file_pkg_pb_post_relation_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/pb/post_relation.proto\x12\rpost_relation\"+\n" +
	"\x11InsertUserRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"\a\n" +
	"\x05Empty2j\n" +
	"\x13PostRelationService\x12S\n" +
	"\x19InsertUserIntoFollowCount\x12 .post_relation.InsertUserRequest\x1a\x14.post_relation.EmptyB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_post_relation_proto_rawDescOnce sync.Once
	file_pkg_pb_post_relation_proto_rawDescData []byte
)

func file_pkg_pb_post_relation_proto_rawDescGZIP() []byte {
	file_pkg_pb_post_relation_proto_rawDescOnce.Do(func() {
		file_pkg_pb_post_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_post_relation_proto_rawDesc), len(file_pkg_pb_post_relation_proto_rawDesc)))
	})
	return file_pkg_pb_post_relation_proto_rawDescData
}

var file_pkg_pb_post_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_post_relation_proto_goTypes = []any{
	(*InsertUserRequest)(nil), // 0: post_relation.InsertUserRequest
	(*Empty)(nil),             // 1: post_relation.Empty
}
var file_pkg_pb_post_relation_proto_depIdxs = []int32{
	0, // 0: post_relation.PostRelationService.InsertUserIntoFollowCount:input_type -> post_relation.InsertUserRequest
	1, // 1: post_relation.PostRelationService.InsertUserIntoFollowCount:output_type -> post_relation.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_post_relation_proto_init() }
func file_pkg_pb_post_relation_proto_init() {
	if File_pkg_pb_post_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_post_relation_proto_rawDesc), len(file_pkg_pb_post_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_post_relation_proto_goTypes,
		DependencyIndexes: file_pkg_pb_post_relation_proto_depIdxs,
		MessageInfos:      file_pkg_pb_post_relation_proto_msgTypes,
	}.Build()
	File_pkg_pb_post_relation_proto = out.File
	file_pkg_pb_post_relation_proto_goTypes = nil
	file_pkg_pb_post_relation_proto_depIdxs = nil
}
