apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  AUTH_SOURCE: "gateway"
  PORT: ":50053"
  AUTH_SUBSCRIPTION_SVC_URL: "auth-service:50051"
  MONGODB_URI: "mongodb+srv://mongodb:mongodb@cluster0.kcemi.mongodb.net/?appName=Cluster0"
  KAFKA_BROKERS: "kafka-2b562aca-chattr.k.aivencloud.com:15035"
  AWS_REGION: "ap-south-1"
  AWS_BUCKET: "chattr-storage-photos"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: chattr-chat_svc:latest
        imagePullPolicy: IfNotPresent      # <--- ADD THIS to ensure it uses the local kind image
        ports:
        - containerPort: 50053
        # Loads all non-sensitive variables from the ConfigMap
        envFrom:
        - configMapRef:
            name: chat-config
        # Explicitly maps sensitive variables from the Secret
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: chat-secrets
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: chat-secrets
              key: AWS_SECRET_ACCESS_KEY
        # These now point to where the volume is mounted below
        - name: KAFKA_CA_CERT
          value: "/etc/certs/ca.pem"
        - name: KAFKA_ACCESS_CERT
          value: "/etc/certs/service.cert"
        - name: KAFKA_ACCESS_KEY
          value: "/etc/certs/service.key"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: cert-volume
          mountPath: "/etc/certs"
          readOnly: true
      volumes:
      - name: cert-volume
        secret:
          secretName: post-relation-secret
          items:
          - key: KAFKA_CA_CERT
            path: ca.pem
          - key: KAFKA_ACCESS_CERT
            path: service.cert
          - key: KAFKA_ACCESS_KEY
            path: service.key