apiVersion: v1
kind: ConfigMap
metadata:
  name: post-relation-config
data:
  PORT: ":50052"
  AUTH_SUBSCRIPTION_SVC_URL: "auth-service:50051"
  DB_HOST: "ep-silent-voice-a1jrocug.ap-southeast-1.aws.neon.tech"
  DB_NAME: "post_relation"
  DB_PORT: "5432"
  DB_USER: "neondb_owner"
  KAFKA_BROKERS: "kafka-2b562aca-chattr.k.aivencloud.com:15035"
  CELEBRITY_FOLLOW_COUNT: "5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-relation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-relation-service
  template:
    metadata:
      labels:
        app: post-relation-service
    spec:
      containers:
      - name: post-relation
        image: ansalps/chattr-post_svc:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 50052
        envFrom:
        - configMapRef:
            name: post-relation-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-relation-secret
              key: DB_PASSWORD
        - name: REDIS_ADDRESS # Mapping the Secret to the variable your Go code expects
          valueFrom:
            secretKeyRef:
              name: post-relation-secret
              key: REDIS_ADDRESS
        # These now point to where the volume is mounted below
        - name: KAFKA_CA_CERT
          value: "/etc/certs/ca.pem"
        - name: KAFKA_ACCESS_CERT
          value: "/etc/certs/service.cert"
        - name: KAFKA_ACCESS_KEY
          value: "/etc/certs/service.key"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: cert-volume
          mountPath: "/etc/certs"
          readOnly: true
      volumes:
      - name: cert-volume
        secret:
          secretName: post-relation-secret
          items:
          - key: KAFKA_CA_CERT
            path: ca.pem
          - key: KAFKA_ACCESS_CERT
            path: service.cert
          - key: KAFKA_ACCESS_KEY
            path: service.key
---
apiVersion: v1
kind: Service
metadata:
  name: post-relation-service
spec:
  selector:
    app: post-relation-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
  type: ClusterIP