// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/auth_subscription.proto

package auth_subscription

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllUsersRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllUsersRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=Bio,proto3" json:"Bio,omitempty"`
	ProfileImgUrl string                 `protobuf:"bytes,6,opt,name=ProfileImgUrl,proto3" json:"ProfileImgUrl,omitempty"`
	Links         string                 `protobuf:"bytes,7,opt,name=Links,proto3" json:"Links,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetProfileImgUrl() string {
	if x != nil {
		return x.ProfileImgUrl
	}
	return ""
}

func (x *User) GetLinks() string {
	if x != nil {
		return x.Links
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAllActiveSubscriptionPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActiveSubscriptionPlansRequest) Reset() {
	*x = GetAllActiveSubscriptionPlansRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActiveSubscriptionPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActiveSubscriptionPlansRequest) ProtoMessage() {}

func (x *GetAllActiveSubscriptionPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActiveSubscriptionPlansRequest.ProtoReflect.Descriptor instead.
func (*GetAllActiveSubscriptionPlansRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllActiveSubscriptionPlansRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllActiveSubscriptionPlansRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllActiveSubscriptionPlansResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubscriptioPlans []*SubscriptioPlan     `protobuf:"bytes,1,rep,name=SubscriptioPlans,proto3" json:"SubscriptioPlans,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllActiveSubscriptionPlansResponse) Reset() {
	*x = GetAllActiveSubscriptionPlansResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActiveSubscriptionPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActiveSubscriptionPlansResponse) ProtoMessage() {}

func (x *GetAllActiveSubscriptionPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActiveSubscriptionPlansResponse.ProtoReflect.Descriptor instead.
func (*GetAllActiveSubscriptionPlansResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllActiveSubscriptionPlansResponse) GetSubscriptioPlans() []*SubscriptioPlan {
	if x != nil {
		return x.SubscriptioPlans
	}
	return nil
}

type GetAllSubscriptionPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubscriptionPlansRequest) Reset() {
	*x = GetAllSubscriptionPlansRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubscriptionPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubscriptionPlansRequest) ProtoMessage() {}

func (x *GetAllSubscriptionPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubscriptionPlansRequest.ProtoReflect.Descriptor instead.
func (*GetAllSubscriptionPlansRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllSubscriptionPlansRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllSubscriptionPlansRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SubscriptioPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	DurationDays  uint64                 `protobuf:"varint,6,opt,name=DurationDays,proto3" json:"DurationDays,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptioPlan) Reset() {
	*x = SubscriptioPlan{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptioPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptioPlan) ProtoMessage() {}

func (x *SubscriptioPlan) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptioPlan.ProtoReflect.Descriptor instead.
func (*SubscriptioPlan) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptioPlan) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubscriptioPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SubscriptioPlan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SubscriptioPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubscriptioPlan) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubscriptioPlan) GetDurationDays() uint64 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *SubscriptioPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubscriptioPlan) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetAllSubscriptionPlansResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubscriptioPlans []*SubscriptioPlan     `protobuf:"bytes,1,rep,name=SubscriptioPlans,proto3" json:"SubscriptioPlans,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllSubscriptionPlansResponse) Reset() {
	*x = GetAllSubscriptionPlansResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubscriptionPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubscriptionPlansResponse) ProtoMessage() {}

func (x *GetAllSubscriptionPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubscriptionPlansResponse.ProtoReflect.Descriptor instead.
func (*GetAllSubscriptionPlansResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllSubscriptionPlansResponse) GetSubscriptioPlans() []*SubscriptioPlan {
	if x != nil {
		return x.SubscriptioPlans
	}
	return nil
}

type DeactivateSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateSubscriptionPlanRequest) Reset() {
	*x = DeactivateSubscriptionPlanRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateSubscriptionPlanRequest) ProtoMessage() {}

func (x *DeactivateSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*DeactivateSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateSubscriptionPlanRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeactivateSubscriptionPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	DurationDays  uint64                 `protobuf:"varint,6,opt,name=DurationDays,proto3" json:"DurationDays,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateSubscriptionPlanResponse) Reset() {
	*x = DeactivateSubscriptionPlanResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateSubscriptionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateSubscriptionPlanResponse) ProtoMessage() {}

func (x *DeactivateSubscriptionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateSubscriptionPlanResponse.ProtoReflect.Descriptor instead.
func (*DeactivateSubscriptionPlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *DeactivateSubscriptionPlanResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeactivateSubscriptionPlanResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeactivateSubscriptionPlanResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DeactivateSubscriptionPlanResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeactivateSubscriptionPlanResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DeactivateSubscriptionPlanResponse) GetDurationDays() uint64 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *DeactivateSubscriptionPlanResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeactivateSubscriptionPlanResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ActivateSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateSubscriptionPlanRequest) Reset() {
	*x = ActivateSubscriptionPlanRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateSubscriptionPlanRequest) ProtoMessage() {}

func (x *ActivateSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*ActivateSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *ActivateSubscriptionPlanRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ActivateSubscriptionPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	DurationDays  uint64                 `protobuf:"varint,6,opt,name=DurationDays,proto3" json:"DurationDays,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateSubscriptionPlanResponse) Reset() {
	*x = ActivateSubscriptionPlanResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateSubscriptionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateSubscriptionPlanResponse) ProtoMessage() {}

func (x *ActivateSubscriptionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateSubscriptionPlanResponse.ProtoReflect.Descriptor instead.
func (*ActivateSubscriptionPlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *ActivateSubscriptionPlanResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivateSubscriptionPlanResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActivateSubscriptionPlanResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ActivateSubscriptionPlanResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivateSubscriptionPlanResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ActivateSubscriptionPlanResponse) GetDurationDays() uint64 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *ActivateSubscriptionPlanResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivateSubscriptionPlanResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	DurationDays  uint64                 `protobuf:"varint,4,opt,name=DurationDays,proto3" json:"DurationDays,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionPlanRequest) Reset() {
	*x = UpdateSubscriptionPlanRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionPlanRequest) ProtoMessage() {}

func (x *UpdateSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSubscriptionPlanRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSubscriptionPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSubscriptionPlanRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateSubscriptionPlanRequest) GetDurationDays() uint64 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpdateSubscriptionPlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateSubscriptionPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	DurationDays  uint64                 `protobuf:"varint,6,opt,name=DurationDays,proto3" json:"DurationDays,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionPlanResponse) Reset() {
	*x = UpdateSubscriptionPlanResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionPlanResponse) ProtoMessage() {}

func (x *UpdateSubscriptionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionPlanResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionPlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSubscriptionPlanResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSubscriptionPlanResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateSubscriptionPlanResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateSubscriptionPlanResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSubscriptionPlanResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateSubscriptionPlanResponse) GetDurationDays() uint64 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpdateSubscriptionPlanResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSubscriptionPlanResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=Period,proto3" json:"Period,omitempty"`
	Interval      uint64                 `protobuf:"varint,5,opt,name=Interval,proto3" json:"Interval,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionPlanRequest) Reset() {
	*x = CreateSubscriptionPlanRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionPlanRequest) ProtoMessage() {}

func (x *CreateSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{14}
}

func (x *CreateSubscriptionPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionPlanRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSubscriptionPlanRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSubscriptionPlanRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *CreateSubscriptionPlanRequest) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *CreateSubscriptionPlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSubscriptionPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Period        string                 `protobuf:"bytes,7,opt,name=Period,proto3" json:"Period,omitempty"`
	Interval      uint64                 `protobuf:"varint,8,opt,name=Interval,proto3" json:"Interval,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=Description,proto3" json:"Description,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionPlanResponse) Reset() {
	*x = CreateSubscriptionPlanResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionPlanResponse) ProtoMessage() {}

func (x *CreateSubscriptionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionPlanResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionPlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSubscriptionPlanResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateSubscriptionPlanResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateSubscriptionPlanResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CreateSubscriptionPlanResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionPlanResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSubscriptionPlanResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSubscriptionPlanResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *CreateSubscriptionPlanResponse) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *CreateSubscriptionPlanResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSubscriptionPlanResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type AdminLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{16}
}

func (x *AdminLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminDetails  *AdminDetails          `protobuf:"bytes,1,opt,name=adminDetails,proto3" json:"adminDetails,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResponse) Reset() {
	*x = AdminLoginResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResponse) ProtoMessage() {}

func (x *AdminLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResponse.ProtoReflect.Descriptor instead.
func (*AdminLoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{17}
}

func (x *AdminLoginResponse) GetAdminDetails() *AdminDetails {
	if x != nil {
		return x.AdminDetails
	}
	return nil
}

func (x *AdminLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AdminLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type AdminDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDetails) Reset() {
	*x = AdminDetails{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDetails) ProtoMessage() {}

func (x *AdminDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDetails.ProtoReflect.Descriptor instead.
func (*AdminDetails) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{18}
}

func (x *AdminDetails) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{19}
}

func (x *UserLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDetails   *UserDetails           `protobuf:"bytes,1,opt,name=userDetails,proto3" json:"userDetails,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{20}
}

func (x *UserLoginResponse) GetUserDetails() *UserDetails {
	if x != nil {
		return x.UserDetails
	}
	return nil
}

func (x *UserLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	BlueTick      bool                   `protobuf:"varint,6,opt,name=BlueTick,proto3" json:"BlueTick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{21}
}

func (x *UserDetails) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDetails) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserDetails) GetBlueTick() bool {
	if x != nil {
		return x.BlueTick
	}
	return false
}

type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{22}
}

func (x *BlockUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{23}
}

func (x *BlockUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnblockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserRequest) Reset() {
	*x = UnblockUserRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserRequest) ProtoMessage() {}

func (x *UnblockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserRequest.ProtoReflect.Descriptor instead.
func (*UnblockUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{24}
}

func (x *UnblockUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnblockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserResponse) Reset() {
	*x = UnblockUserResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserResponse) ProtoMessage() {}

func (x *UnblockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserResponse.ProtoReflect.Descriptor instead.
func (*UnblockUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{25}
}

func (x *UnblockUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserSignUpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserName        string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,5,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSignUpRequest) Reset() {
	*x = UserSignUpRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpRequest) ProtoMessage() {}

func (x *UserSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpRequest.ProtoReflect.Descriptor instead.
func (*UserSignUpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{26}
}

func (x *UserSignUpRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserSignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserSignUpRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UserSignUpResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	OtpVerificationToken string                 `protobuf:"bytes,5,opt,name=OtpVerificationToken,proto3" json:"OtpVerificationToken,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserSignUpResponse) Reset() {
	*x = UserSignUpResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpResponse) ProtoMessage() {}

func (x *UserSignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpResponse.ProtoReflect.Descriptor instead.
func (*UserSignUpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{27}
}

func (x *UserSignUpResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSignUpResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserSignUpResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSignUpResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSignUpResponse) GetOtpVerificationToken() string {
	if x != nil {
		return x.OtpVerificationToken
	}
	return ""
}

type OtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OtpCode       uint64                 `protobuf:"varint,2,opt,name=OtpCode,proto3" json:"OtpCode,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=Purpose,proto3" json:"Purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpRequest) Reset() {
	*x = OtpRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpRequest) ProtoMessage() {}

func (x *OtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpRequest.ProtoReflect.Descriptor instead.
func (*OtpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{28}
}

func (x *OtpRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OtpRequest) GetOtpCode() uint64 {
	if x != nil {
		return x.OtpCode
	}
	return 0
}

func (x *OtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OtpRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type OtpVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	TempToken     string                 `protobuf:"bytes,5,opt,name=TempToken,proto3" json:"TempToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpVerificationResponse) Reset() {
	*x = OtpVerificationResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpVerificationResponse) ProtoMessage() {}

func (x *OtpVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpVerificationResponse.ProtoReflect.Descriptor instead.
func (*OtpVerificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{29}
}

func (x *OtpVerificationResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OtpVerificationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OtpVerificationResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OtpVerificationResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OtpVerificationResponse) GetTempToken() string {
	if x != nil {
		return x.TempToken
	}
	return ""
}

type ResendOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendOtpRequest) Reset() {
	*x = ResendOtpRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendOtpRequest) ProtoMessage() {}

func (x *ResendOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendOtpRequest.ProtoReflect.Descriptor instead.
func (*ResendOtpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{30}
}

func (x *ResendOtpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResendOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResendOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendOtpResponse) Reset() {
	*x = ResendOtpResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendOtpResponse) ProtoMessage() {}

func (x *ResendOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendOtpResponse.ProtoReflect.Descriptor instead.
func (*ResendOtpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{31}
}

func (x *ResendOtpResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AccessRegeneratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRegeneratorRequest) Reset() {
	*x = AccessRegeneratorRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRegeneratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRegeneratorRequest) ProtoMessage() {}

func (x *AccessRegeneratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRegeneratorRequest.ProtoReflect.Descriptor instead.
func (*AccessRegeneratorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{32}
}

func (x *AccessRegeneratorRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccessRegeneratorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccessRegeneratorRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AccessRegeneratorResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	NewAccessToken string                 `protobuf:"bytes,4,opt,name=NewAccessToken,proto3" json:"NewAccessToken,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccessRegeneratorResponse) Reset() {
	*x = AccessRegeneratorResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRegeneratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRegeneratorResponse) ProtoMessage() {}

func (x *AccessRegeneratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRegeneratorResponse.ProtoReflect.Descriptor instead.
func (*AccessRegeneratorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{33}
}

func (x *AccessRegeneratorResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccessRegeneratorResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccessRegeneratorResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AccessRegeneratorResponse) GetNewAccessToken() string {
	if x != nil {
		return x.NewAccessToken
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{34}
}

func (x *ResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_subscription_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_subscription_proto_rawDescGZIP(), []int{35}
}

func (x *ResetPasswordResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_pkg_proto_auth_subscription_proto protoreflect.FileDescriptor

const file_pkg_proto_auth_subscription_proto_rawDesc = "" +
	"\n" +
	"!pkg/proto/auth_subscription.proto\x12\x11auth_subscription\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x12GetAllUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"D\n" +
	"\x13GetAllUsersResponse\x12-\n" +
	"\x05Users\x18\x01 \x03(\v2\x17.auth_subscription.UserR\x05Users\"\xc2\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bUserName\x18\x03 \x01(\tR\bUserName\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x12\x10\n" +
	"\x03Bio\x18\x05 \x01(\tR\x03Bio\x12$\n" +
	"\rProfileImgUrl\x18\x06 \x01(\tR\rProfileImgUrl\x12\x14\n" +
	"\x05Links\x18\a \x01(\tR\x05Links\x12\x16\n" +
	"\x06Status\x18\b \x01(\tR\x06Status\"T\n" +
	"$GetAllActiveSubscriptionPlansRequest\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x04R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x04R\x06Offset\"w\n" +
	"%GetAllActiveSubscriptionPlansResponse\x12N\n" +
	"\x10SubscriptioPlans\x18\x01 \x03(\v2\".auth_subscription.SubscriptioPlanR\x10SubscriptioPlans\"N\n" +
	"\x1eGetAllSubscriptionPlansRequest\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x04R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x04R\x06Offset\"\xa1\x02\n" +
	"\x0fSubscriptioPlan\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x02R\x05Price\x12\"\n" +
	"\fDurationDays\x18\x06 \x01(\x04R\fDurationDays\x12 \n" +
	"\vDescription\x18\a \x01(\tR\vDescription\x12\x1a\n" +
	"\bIsActive\x18\b \x01(\bR\bIsActive\"q\n" +
	"\x1fGetAllSubscriptionPlansResponse\x12N\n" +
	"\x10SubscriptioPlans\x18\x01 \x03(\v2\".auth_subscription.SubscriptioPlanR\x10SubscriptioPlans\"3\n" +
	"!DeactivateSubscriptionPlanRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\"\xb4\x02\n" +
	"\"DeactivateSubscriptionPlanResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x02R\x05Price\x12\"\n" +
	"\fDurationDays\x18\x06 \x01(\x04R\fDurationDays\x12 \n" +
	"\vDescription\x18\a \x01(\tR\vDescription\x12\x1a\n" +
	"\bIsActive\x18\b \x01(\bR\bIsActive\"1\n" +
	"\x1fActivateSubscriptionPlanRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\"\xb2\x02\n" +
	" ActivateSubscriptionPlanResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x02R\x05Price\x12\"\n" +
	"\fDurationDays\x18\x06 \x01(\x04R\fDurationDays\x12 \n" +
	"\vDescription\x18\a \x01(\tR\vDescription\x12\x1a\n" +
	"\bIsActive\x18\b \x01(\bR\bIsActive\"\x9f\x01\n" +
	"\x1dUpdateSubscriptionPlanRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x02R\x05Price\x12\"\n" +
	"\fDurationDays\x18\x04 \x01(\x04R\fDurationDays\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\"\xb0\x02\n" +
	"\x1eUpdateSubscriptionPlanResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x02R\x05Price\x12\"\n" +
	"\fDurationDays\x18\x06 \x01(\x04R\fDurationDays\x12 \n" +
	"\vDescription\x18\a \x01(\tR\vDescription\x12\x1a\n" +
	"\bIsActive\x18\b \x01(\bR\bIsActive\"\xbb\x01\n" +
	"\x1dCreateSubscriptionPlanRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\x03R\x05Price\x12\x1a\n" +
	"\bCurrency\x18\x03 \x01(\tR\bCurrency\x12\x16\n" +
	"\x06Period\x18\x04 \x01(\tR\x06Period\x12\x1a\n" +
	"\bInterval\x18\x05 \x01(\x04R\bInterval\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\"\xdc\x02\n" +
	"\x1eCreateSubscriptionPlanResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x03R\x05Price\x12\x1a\n" +
	"\bCurrency\x18\x06 \x01(\tR\bCurrency\x12\x16\n" +
	"\x06Period\x18\a \x01(\tR\x06Period\x12\x1a\n" +
	"\bInterval\x18\b \x01(\x04R\bInterval\x12 \n" +
	"\vDescription\x18\t \x01(\tR\vDescription\x12\x1a\n" +
	"\bIsActive\x18\n" +
	" \x01(\bR\bIsActive\"E\n" +
	"\x11AdminLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9f\x01\n" +
	"\x12AdminLoginResponse\x12C\n" +
	"\fadminDetails\x18\x01 \x01(\v2\x1f.auth_subscription.AdminDetailsR\fadminDetails\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x03 \x01(\tR\fRefreshToken\"4\n" +
	"\fAdminDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"D\n" +
	"\x10UserLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9b\x01\n" +
	"\x11UserLoginResponse\x12@\n" +
	"\vuserDetails\x18\x01 \x01(\v2\x1e.auth_subscription.UserDetailsR\vuserDetails\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x03 \x01(\tR\fRefreshToken\"\x97\x01\n" +
	"\vUserDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bUserName\x18\x03 \x01(\tR\bUserName\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\tR\x06Status\x12\x1a\n" +
	"\bBlueTick\x18\x06 \x01(\bR\bBlueTick\"*\n" +
	"\x10BlockUserRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"+\n" +
	"\x11BlockUserResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\",\n" +
	"\x12UnblockUserRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"-\n" +
	"\x13UnblockUserResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"\x9f\x01\n" +
	"\x11UserSignUpRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12(\n" +
	"\x0fConfirmPassword\x18\x05 \x01(\tR\x0fConfirmPassword\"\x9e\x01\n" +
	"\x12UserSignUpResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x122\n" +
	"\x14OtpVerificationToken\x18\x05 \x01(\tR\x14OtpVerificationToken\"n\n" +
	"\n" +
	"OtpRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aOtpCode\x18\x02 \x01(\x04R\aOtpCode\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x18\n" +
	"\aPurpose\x18\x04 \x01(\tR\aPurpose\"\xab\x01\n" +
	"\x17OtpVerificationResponse\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x12 \n" +
	"\vAccessToken\x18\x03 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x04 \x01(\tR\fRefreshToken\x12\x1c\n" +
	"\tTempToken\x18\x05 \x01(\tR\tTempToken\"<\n" +
	"\x10ResendOtpRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\")\n" +
	"\x11ResendOtpResponse\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\"T\n" +
	"\x18AccessRegeneratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x12\n" +
	"\x04Role\x18\x03 \x01(\tR\x04Role\"}\n" +
	"\x19AccessRegeneratorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x12\n" +
	"\x04Role\x18\x03 \x01(\tR\x04Role\x12&\n" +
	"\x0eNewAccessToken\x18\x04 \x01(\tR\x0eNewAccessToken\"H\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"-\n" +
	"\x15ResetPasswordResponse\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email2\xe7\r\n" +
	"\x17AuthSubscriptionService\x12Y\n" +
	"\n" +
	"AdminLogin\x12$.auth_subscription.AdminLoginRequest\x1a%.auth_subscription.AdminLoginResponse\x12V\n" +
	"\tBlockUser\x12#.auth_subscription.BlockUserRequest\x1a$.auth_subscription.BlockUserResponse\x12\\\n" +
	"\vUnblockUser\x12%.auth_subscription.UnblockUserRequest\x1a&.auth_subscription.UnblockUserResponse\x12\\\n" +
	"\vGetAllUsers\x12%.auth_subscription.GetAllUsersRequest\x1a&.auth_subscription.GetAllUsersResponse\x12}\n" +
	"\x16CreateSubscriptionPlan\x120.auth_subscription.CreateSubscriptionPlanRequest\x1a1.auth_subscription.CreateSubscriptionPlanResponse\x12}\n" +
	"\x16UpdateSubscriptionPlan\x120.auth_subscription.UpdateSubscriptionPlanRequest\x1a1.auth_subscription.UpdateSubscriptionPlanResponse\x12\x83\x01\n" +
	"\x18ActivateSubscriptionPlan\x122.auth_subscription.ActivateSubscriptionPlanRequest\x1a3.auth_subscription.ActivateSubscriptionPlanResponse\x12\x89\x01\n" +
	"\x1aDeactivateSubscriptionPlan\x124.auth_subscription.DeactivateSubscriptionPlanRequest\x1a5.auth_subscription.DeactivateSubscriptionPlanResponse\x12\x80\x01\n" +
	"\x17GetAllSubscriptionPlans\x121.auth_subscription.GetAllSubscriptionPlansRequest\x1a2.auth_subscription.GetAllSubscriptionPlansResponse\x12Y\n" +
	"\n" +
	"UserSignUp\x12$.auth_subscription.UserSignUpRequest\x1a%.auth_subscription.UserSignUpResponse\x12V\n" +
	"\tVerifyOtp\x12\x1d.auth_subscription.OtpRequest\x1a*.auth_subscription.OtpVerificationResponse\x12V\n" +
	"\tResendOtp\x12#.auth_subscription.ResendOtpRequest\x1a$.auth_subscription.ResendOtpResponse\x12n\n" +
	"\x11AccessRegenerator\x12+.auth_subscription.AccessRegeneratorRequest\x1a,.auth_subscription.AccessRegeneratorResponse\x12b\n" +
	"\rResetPassword\x12'.auth_subscription.ResetPasswordRequest\x1a(.auth_subscription.ResetPasswordResponse\x12V\n" +
	"\tUserLogin\x12#.auth_subscription.UserLoginRequest\x1a$.auth_subscription.UserLoginResponse\x12\x92\x01\n" +
	"\x1dGetAllActiveSubscriptionPlans\x127.auth_subscription.GetAllActiveSubscriptionPlansRequest\x1a8.auth_subscription.GetAllActiveSubscriptionPlansResponseB\x1cZ\x1a./pkg/pb/auth_subscriptionb\x06proto3"

var (
	file_pkg_proto_auth_subscription_proto_rawDescOnce sync.Once
	file_pkg_proto_auth_subscription_proto_rawDescData []byte
)

func file_pkg_proto_auth_subscription_proto_rawDescGZIP() []byte {
	file_pkg_proto_auth_subscription_proto_rawDescOnce.Do(func() {
		file_pkg_proto_auth_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_auth_subscription_proto_rawDesc), len(file_pkg_proto_auth_subscription_proto_rawDesc)))
	})
	return file_pkg_proto_auth_subscription_proto_rawDescData
}

var file_pkg_proto_auth_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_pkg_proto_auth_subscription_proto_goTypes = []any{
	(*GetAllUsersRequest)(nil),                    // 0: auth_subscription.GetAllUsersRequest
	(*GetAllUsersResponse)(nil),                   // 1: auth_subscription.GetAllUsersResponse
	(*User)(nil),                                  // 2: auth_subscription.User
	(*GetAllActiveSubscriptionPlansRequest)(nil),  // 3: auth_subscription.GetAllActiveSubscriptionPlansRequest
	(*GetAllActiveSubscriptionPlansResponse)(nil), // 4: auth_subscription.GetAllActiveSubscriptionPlansResponse
	(*GetAllSubscriptionPlansRequest)(nil),        // 5: auth_subscription.GetAllSubscriptionPlansRequest
	(*SubscriptioPlan)(nil),                       // 6: auth_subscription.SubscriptioPlan
	(*GetAllSubscriptionPlansResponse)(nil),       // 7: auth_subscription.GetAllSubscriptionPlansResponse
	(*DeactivateSubscriptionPlanRequest)(nil),     // 8: auth_subscription.DeactivateSubscriptionPlanRequest
	(*DeactivateSubscriptionPlanResponse)(nil),    // 9: auth_subscription.DeactivateSubscriptionPlanResponse
	(*ActivateSubscriptionPlanRequest)(nil),       // 10: auth_subscription.ActivateSubscriptionPlanRequest
	(*ActivateSubscriptionPlanResponse)(nil),      // 11: auth_subscription.ActivateSubscriptionPlanResponse
	(*UpdateSubscriptionPlanRequest)(nil),         // 12: auth_subscription.UpdateSubscriptionPlanRequest
	(*UpdateSubscriptionPlanResponse)(nil),        // 13: auth_subscription.UpdateSubscriptionPlanResponse
	(*CreateSubscriptionPlanRequest)(nil),         // 14: auth_subscription.CreateSubscriptionPlanRequest
	(*CreateSubscriptionPlanResponse)(nil),        // 15: auth_subscription.CreateSubscriptionPlanResponse
	(*AdminLoginRequest)(nil),                     // 16: auth_subscription.AdminLoginRequest
	(*AdminLoginResponse)(nil),                    // 17: auth_subscription.AdminLoginResponse
	(*AdminDetails)(nil),                          // 18: auth_subscription.AdminDetails
	(*UserLoginRequest)(nil),                      // 19: auth_subscription.UserLoginRequest
	(*UserLoginResponse)(nil),                     // 20: auth_subscription.UserLoginResponse
	(*UserDetails)(nil),                           // 21: auth_subscription.UserDetails
	(*BlockUserRequest)(nil),                      // 22: auth_subscription.BlockUserRequest
	(*BlockUserResponse)(nil),                     // 23: auth_subscription.BlockUserResponse
	(*UnblockUserRequest)(nil),                    // 24: auth_subscription.UnblockUserRequest
	(*UnblockUserResponse)(nil),                   // 25: auth_subscription.UnblockUserResponse
	(*UserSignUpRequest)(nil),                     // 26: auth_subscription.UserSignUpRequest
	(*UserSignUpResponse)(nil),                    // 27: auth_subscription.UserSignUpResponse
	(*OtpRequest)(nil),                            // 28: auth_subscription.OtpRequest
	(*OtpVerificationResponse)(nil),               // 29: auth_subscription.OtpVerificationResponse
	(*ResendOtpRequest)(nil),                      // 30: auth_subscription.ResendOtpRequest
	(*ResendOtpResponse)(nil),                     // 31: auth_subscription.ResendOtpResponse
	(*AccessRegeneratorRequest)(nil),              // 32: auth_subscription.AccessRegeneratorRequest
	(*AccessRegeneratorResponse)(nil),             // 33: auth_subscription.AccessRegeneratorResponse
	(*ResetPasswordRequest)(nil),                  // 34: auth_subscription.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),                 // 35: auth_subscription.ResetPasswordResponse
	(*timestamppb.Timestamp)(nil),                 // 36: google.protobuf.Timestamp
}
var file_pkg_proto_auth_subscription_proto_depIdxs = []int32{
	2,  // 0: auth_subscription.GetAllUsersResponse.Users:type_name -> auth_subscription.User
	6,  // 1: auth_subscription.GetAllActiveSubscriptionPlansResponse.SubscriptioPlans:type_name -> auth_subscription.SubscriptioPlan
	36, // 2: auth_subscription.SubscriptioPlan.CreatedAt:type_name -> google.protobuf.Timestamp
	36, // 3: auth_subscription.SubscriptioPlan.UpdatedAt:type_name -> google.protobuf.Timestamp
	6,  // 4: auth_subscription.GetAllSubscriptionPlansResponse.SubscriptioPlans:type_name -> auth_subscription.SubscriptioPlan
	36, // 5: auth_subscription.DeactivateSubscriptionPlanResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	36, // 6: auth_subscription.DeactivateSubscriptionPlanResponse.UpdatedAt:type_name -> google.protobuf.Timestamp
	36, // 7: auth_subscription.ActivateSubscriptionPlanResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	36, // 8: auth_subscription.ActivateSubscriptionPlanResponse.UpdatedAt:type_name -> google.protobuf.Timestamp
	36, // 9: auth_subscription.UpdateSubscriptionPlanResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	36, // 10: auth_subscription.UpdateSubscriptionPlanResponse.UpdatedAt:type_name -> google.protobuf.Timestamp
	36, // 11: auth_subscription.CreateSubscriptionPlanResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	36, // 12: auth_subscription.CreateSubscriptionPlanResponse.UpdatedAt:type_name -> google.protobuf.Timestamp
	18, // 13: auth_subscription.AdminLoginResponse.adminDetails:type_name -> auth_subscription.AdminDetails
	21, // 14: auth_subscription.UserLoginResponse.userDetails:type_name -> auth_subscription.UserDetails
	16, // 15: auth_subscription.AuthSubscriptionService.AdminLogin:input_type -> auth_subscription.AdminLoginRequest
	22, // 16: auth_subscription.AuthSubscriptionService.BlockUser:input_type -> auth_subscription.BlockUserRequest
	24, // 17: auth_subscription.AuthSubscriptionService.UnblockUser:input_type -> auth_subscription.UnblockUserRequest
	0,  // 18: auth_subscription.AuthSubscriptionService.GetAllUsers:input_type -> auth_subscription.GetAllUsersRequest
	14, // 19: auth_subscription.AuthSubscriptionService.CreateSubscriptionPlan:input_type -> auth_subscription.CreateSubscriptionPlanRequest
	12, // 20: auth_subscription.AuthSubscriptionService.UpdateSubscriptionPlan:input_type -> auth_subscription.UpdateSubscriptionPlanRequest
	10, // 21: auth_subscription.AuthSubscriptionService.ActivateSubscriptionPlan:input_type -> auth_subscription.ActivateSubscriptionPlanRequest
	8,  // 22: auth_subscription.AuthSubscriptionService.DeactivateSubscriptionPlan:input_type -> auth_subscription.DeactivateSubscriptionPlanRequest
	5,  // 23: auth_subscription.AuthSubscriptionService.GetAllSubscriptionPlans:input_type -> auth_subscription.GetAllSubscriptionPlansRequest
	26, // 24: auth_subscription.AuthSubscriptionService.UserSignUp:input_type -> auth_subscription.UserSignUpRequest
	28, // 25: auth_subscription.AuthSubscriptionService.VerifyOtp:input_type -> auth_subscription.OtpRequest
	30, // 26: auth_subscription.AuthSubscriptionService.ResendOtp:input_type -> auth_subscription.ResendOtpRequest
	32, // 27: auth_subscription.AuthSubscriptionService.AccessRegenerator:input_type -> auth_subscription.AccessRegeneratorRequest
	34, // 28: auth_subscription.AuthSubscriptionService.ResetPassword:input_type -> auth_subscription.ResetPasswordRequest
	19, // 29: auth_subscription.AuthSubscriptionService.UserLogin:input_type -> auth_subscription.UserLoginRequest
	3,  // 30: auth_subscription.AuthSubscriptionService.GetAllActiveSubscriptionPlans:input_type -> auth_subscription.GetAllActiveSubscriptionPlansRequest
	17, // 31: auth_subscription.AuthSubscriptionService.AdminLogin:output_type -> auth_subscription.AdminLoginResponse
	23, // 32: auth_subscription.AuthSubscriptionService.BlockUser:output_type -> auth_subscription.BlockUserResponse
	25, // 33: auth_subscription.AuthSubscriptionService.UnblockUser:output_type -> auth_subscription.UnblockUserResponse
	1,  // 34: auth_subscription.AuthSubscriptionService.GetAllUsers:output_type -> auth_subscription.GetAllUsersResponse
	15, // 35: auth_subscription.AuthSubscriptionService.CreateSubscriptionPlan:output_type -> auth_subscription.CreateSubscriptionPlanResponse
	13, // 36: auth_subscription.AuthSubscriptionService.UpdateSubscriptionPlan:output_type -> auth_subscription.UpdateSubscriptionPlanResponse
	11, // 37: auth_subscription.AuthSubscriptionService.ActivateSubscriptionPlan:output_type -> auth_subscription.ActivateSubscriptionPlanResponse
	9,  // 38: auth_subscription.AuthSubscriptionService.DeactivateSubscriptionPlan:output_type -> auth_subscription.DeactivateSubscriptionPlanResponse
	7,  // 39: auth_subscription.AuthSubscriptionService.GetAllSubscriptionPlans:output_type -> auth_subscription.GetAllSubscriptionPlansResponse
	27, // 40: auth_subscription.AuthSubscriptionService.UserSignUp:output_type -> auth_subscription.UserSignUpResponse
	29, // 41: auth_subscription.AuthSubscriptionService.VerifyOtp:output_type -> auth_subscription.OtpVerificationResponse
	31, // 42: auth_subscription.AuthSubscriptionService.ResendOtp:output_type -> auth_subscription.ResendOtpResponse
	33, // 43: auth_subscription.AuthSubscriptionService.AccessRegenerator:output_type -> auth_subscription.AccessRegeneratorResponse
	35, // 44: auth_subscription.AuthSubscriptionService.ResetPassword:output_type -> auth_subscription.ResetPasswordResponse
	20, // 45: auth_subscription.AuthSubscriptionService.UserLogin:output_type -> auth_subscription.UserLoginResponse
	4,  // 46: auth_subscription.AuthSubscriptionService.GetAllActiveSubscriptionPlans:output_type -> auth_subscription.GetAllActiveSubscriptionPlansResponse
	31, // [31:47] is the sub-list for method output_type
	15, // [15:31] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_proto_auth_subscription_proto_init() }
func file_pkg_proto_auth_subscription_proto_init() {
	if File_pkg_proto_auth_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_auth_subscription_proto_rawDesc), len(file_pkg_proto_auth_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_auth_subscription_proto_goTypes,
		DependencyIndexes: file_pkg_proto_auth_subscription_proto_depIdxs,
		MessageInfos:      file_pkg_proto_auth_subscription_proto_msgTypes,
	}.Build()
	File_pkg_proto_auth_subscription_proto = out.File
	file_pkg_proto_auth_subscription_proto_goTypes = nil
	file_pkg_proto_auth_subscription_proto_depIdxs = nil
}
