// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/post_relation.proto

package post_relation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=Caption,proto3" json:"Caption,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_pkg_proto_post_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_relation_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *CreatePostRequest) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_pkg_proto_post_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_relation_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

var File_pkg_proto_post_relation_proto protoreflect.FileDescriptor

const file_pkg_proto_post_relation_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/post_relation.proto\x12\rpost_relation\"d\n" +
	"\x11CreatePostRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aCaption\x18\x02 \x01(\tR\aCaption\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\",\n" +
	"\x12CreatePostResponse\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x04R\x06PostId2h\n" +
	"\x13PostRelationService\x12Q\n" +
	"\n" +
	"CreatePost\x12 .post_relation.CreatePostRequest\x1a!.post_relation.CreatePostResponseB\x18Z\x16./pkg/pb/post_relationb\x06proto3"

var (
	file_pkg_proto_post_relation_proto_rawDescOnce sync.Once
	file_pkg_proto_post_relation_proto_rawDescData []byte
)

func file_pkg_proto_post_relation_proto_rawDescGZIP() []byte {
	file_pkg_proto_post_relation_proto_rawDescOnce.Do(func() {
		file_pkg_proto_post_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_post_relation_proto_rawDesc), len(file_pkg_proto_post_relation_proto_rawDesc)))
	})
	return file_pkg_proto_post_relation_proto_rawDescData
}

var file_pkg_proto_post_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_post_relation_proto_goTypes = []any{
	(*CreatePostRequest)(nil),  // 0: post_relation.CreatePostRequest
	(*CreatePostResponse)(nil), // 1: post_relation.CreatePostResponse
}
var file_pkg_proto_post_relation_proto_depIdxs = []int32{
	0, // 0: post_relation.PostRelationService.CreatePost:input_type -> post_relation.CreatePostRequest
	1, // 1: post_relation.PostRelationService.CreatePost:output_type -> post_relation.CreatePostResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_post_relation_proto_init() }
func file_pkg_proto_post_relation_proto_init() {
	if File_pkg_proto_post_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_post_relation_proto_rawDesc), len(file_pkg_proto_post_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_post_relation_proto_goTypes,
		DependencyIndexes: file_pkg_proto_post_relation_proto_depIdxs,
		MessageInfos:      file_pkg_proto_post_relation_proto_msgTypes,
	}.Build()
	File_pkg_proto_post_relation_proto = out.File
	file_pkg_proto_post_relation_proto_goTypes = nil
	file_pkg_proto_post_relation_proto_depIdxs = nil
}
